## Импорт библиотек

In [40]:
from src.config.config import DATA_FULL_PATH
from src.app.utils.db_manager import DatabaseManager
from src.app.utils.csv_analyser import CSVAnalyser

In [41]:
from warnings import filterwarnings

filterwarnings('ignore', category=UserWarning, message='.*pandas only supports SQLAlchemy connectable.*')

In [42]:
db_manager = DatabaseManager()
csv_analyser = CSVAnalyser(data_path=DATA_FULL_PATH)

В файле HomeCredit_columns_description.csv находится описание каждого столбца, эта информация нужна для определения типов данных для столбцов. Были изучены остальные csv-файлы. Для создания каждой таблицы будет следующий пайплайн:

1. загрузить CSV-файл и изучить его через pandas
2. создать таблицу и описать типы данных
3. загрузить данные из csv-файла
4. вывести данные из созданной таблицы

## Файл bureau.csv

In [43]:
table_name = "bureau"
csv_analyser.analyse_file(f"{table_name}.csv")

Название файла: bureau.csv
Данные: 1716428 строк, 17 столбцов
Столбец SK_ID_CURR
- Описание: ID of loan in our sample - one loan in our sample can have 0,1,2 or more related previous credits in credit bureau
- Особенности: hashed
- Тип данных: int64
- Уникальных значений: 305811
- Null значений: 0 (0.00%)
- Min: 100001
- Max: 456255
Столбец SK_ID_BUREAU
- Тип данных: int64
- Уникальных значений: 1716428
- Null значений: 0 (0.00%)
- Min: 5000000
- Max: 6843457
Столбец CREDIT_ACTIVE
- Описание: Status of the Credit Bureau (CB) reported credits
- Тип данных: object
- Уникальных значений: 4
- Null значений: 0 (0.00%)
- Примеры значений: ['Closed' 'Active' 'Sold' 'Bad debt']
Столбец CREDIT_CURRENCY
- Описание: Recoded currency of the Credit Bureau credit
- Особенности: recoded
- Тип данных: object
- Уникальных значений: 4
- Null значений: 0 (0.00%)
- Примеры значений: ['currency 1' 'currency 2' 'currency 4' 'currency 3']
Столбец DAYS_CREDIT
- Описание: How many days before current application did client apply for Credit Bureau credit
- Особенности: time only relative to the application
- Тип данных: int64
- Уникальных значений: 2923
- Null значений: 0 (0.00%)
- Min: -2922
- Max: 0
Столбец CREDIT_DAY_OVERDUE
- Описание: Number of days past due on CB credit at the time of application for related loan in our sample
- Тип данных: int64
- Уникальных значений: 942
- Null значений: 0 (0.00%)
- Min: 0
- Max: 2792
Столбец DAYS_CREDIT_ENDDATE
- Описание: Remaining duration of CB credit (in days) at the time of application in Home Credit
- Особенности: time only relative to the application
- Тип данных: float64
- Уникальных значений: 14096
- Null значений: 105553 (6.15%)
- Min: -42060.0
- Max: 31199.0
Столбец DAYS_ENDDATE_FACT
- Описание: Days since CB credit ended at the time of application in Home Credit (only for closed credit)
- Особенности: time only relative to the application
- Тип данных: float64
- Уникальных значений: 2917
- Null значений: 633653 (36.92%)
- Min: -42023.0
- Max: 0.0
Столбец AMT_CREDIT_MAX_OVERDUE
- Описание: Maximal amount overdue on the Credit Bureau credit so far (at application date of loan in our sample)
- Тип данных: float64
- Уникальных значений: 68251
- Null значений: 1124488 (65.51%)
- Min: 0.0
- Max: 115987185.0
Столбец CNT_CREDIT_PROLONG
- Описание: How many times was the Credit Bureau credit prolonged
- Тип данных: int64
- Уникальных значений: 10
- Null значений: 0 (0.00%)
- Min: 0
- Max: 9
Столбец AMT_CREDIT_SUM
- Описание: Current credit amount for the Credit Bureau credit
- Тип данных: float64
- Уникальных значений: 236708
- Null значений: 13 (0.00%)
- Min: 0.0
- Max: 585000000.0
Столбец AMT_CREDIT_SUM_DEBT
- Описание: Current debt on Credit Bureau credit
- Тип данных: float64
- Уникальных значений: 226537
- Null значений: 257669 (15.01%)
- Min: -4705600.32
- Max: 170100000.0
Столбец AMT_CREDIT_SUM_LIMIT
- Описание: Current credit limit of credit card reported in Credit Bureau
- Тип данных: float64
- Уникальных значений: 51726
- Null значений: 591780 (34.48%)
- Min: -586406.115
- Max: 4705600.32
Столбец AMT_CREDIT_SUM_OVERDUE
- Описание: Current amount overdue on Credit Bureau credit
- Тип данных: float64
- Уникальных значений: 1616
- Null значений: 0 (0.00%)
- Min: 0.0
- Max: 3756681.0
Столбец CREDIT_TYPE
- Описание: Type of Credit Bureau credit (Car, cash,...)
- Тип данных: object
- Уникальных значений: 15
- Null значений: 0 (0.00%)
- Примеры значений: ['Consumer credit' 'Credit card' 'Mortgage' 'Car loan' 'Microloan']
Столбец DAYS_CREDIT_UPDATE
- Описание: How many days before loan application did last information about the Credit Bureau credit come
- Особенности: time only relative to the application
- Тип данных: int64
- Уникальных значений: 2982
- Null значений: 0 (0.00%)
- Min: -41947
- Max: 372
Столбец AMT_ANNUITY
- Описание: Annuity of the Credit Bureau credit
- Тип данных: float64
- Уникальных значений: 40321
- Null значений: 1226791 (71.47%)
- Min: 0.0
- Max: 118453423.5

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.00,0.0,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.00,171342.0,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.50,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.00,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.00,NaN,NaN,0.0,Consumer credit,-21,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1716423,259355,5057750,Active,currency 1,-44,0,-30.0,NaN,0.0,0,11250.00,11250.0,0.0,0.0,Microloan,-19,NaN
1716424,100044,5057754,Closed,currency 1,-2648,0,-2433.0,-2493.0,5476.5,0,38130.84,0.0,0.0,0.0,Consumer credit,-2493,NaN
1716425,100044,5057762,Closed,currency 1,-1809,0,-1628.0,-970.0,NaN,0,15570.00,NaN,NaN,0.0,Consumer credit,-967,NaN
1716426,246829,5057770,Closed,currency 1,-1878,0,-1513.0,-1513.0,NaN,0,36000.00,0.0,0.0,0.0,Consumer credit,-1508,NaN
1716427,246829,5057778,Closed,currency 1,-463,0,NaN,-387.0,NaN,0,22500.00,0.0,NaN,0.0,Microloan,-387,NaN

SQL-запрос для создания таблицы

- SK_ID_CURR, SK_ID_BUREAU - integer (Стандартный 4-байтовый тип, который может хранить значения до 6.8 млн (лимит integer - 2.1 млрд))
- CREDIT_ACTIVE - varchar(8) (самое длинное значение 'Bad debt' состоит из 8 символов)
- CREDIT_CURRENCY - varchar(11) (самое длинное значение 'currency 4' состоит из 10 символов, но лучше взять с запасом для значений 'currency 10')
- CREDIT_TYPE - varchar(50) (могут быть длинные категории)
- DAYS_CREDIT, CREDIT_DAY_OVERDUE, CNT_CREDIT_PROLONG - smallint (значения не превышают лимит типа в 32767.)
- DAYS_CREDIT_UPDATE - integer (минимальное значение -41947 выходит за нижний предел smallint)
- AMT_... и DAYS_... - real (универсальный выбор для дробных сумм и дней с NULL-значениями)

In [ ]:
table_name = "bureau"
sql_schema_query = f"""
    DROP TABLE IF EXISTS {table_name}; 
    CREATE TABLE {table_name}(
        SK_ID_CURR integer,
        SK_ID_BUREAU integer,
        CREDIT_ACTIVE varchar(8),
        CREDIT_CURRENCY varchar(11),
        DAYS_CREDIT smallint,
        CREDIT_DAY_OVERDUE smallint,
        DAYS_CREDIT_ENDDATE real,
        DAYS_ENDDATE_FACT real,
        AMT_CREDIT_MAX_OVERDUE real,
        CNT_CREDIT_PROLONG smallint,
        AMT_CREDIT_SUM real,
        AMT_CREDIT_SUM_DEBT real,
        AMT_CREDIT_SUM_LIMIT real,
        AMT_CREDIT_SUM_OVERDUE real,
        CREDIT_TYPE varchar(50),
        DAYS_CREDIT_UPDATE integer,
        AMT_ANNUITY  real)
"""

db_manager.send_sql_query(sql_schema_query)

Время выполнения: 0:00:00

SQL-запрос для заполнения таблицы данными из csv-файла

In [ ]:
table_name = "bureau"
sql_data_query = f"""
    COPY {table_name}(
        SK_ID_CURR,
        SK_ID_BUREAU,
        CREDIT_ACTIVE,
        CREDIT_CURRENCY,
        DAYS_CREDIT,
        CREDIT_DAY_OVERDUE,
        DAYS_CREDIT_ENDDATE,
        DAYS_ENDDATE_FACT,
        AMT_CREDIT_MAX_OVERDUE,
        CNT_CREDIT_PROLONG,
        AMT_CREDIT_SUM,
        AMT_CREDIT_SUM_DEBT,
        AMT_CREDIT_SUM_LIMIT,
        AMT_CREDIT_SUM_OVERDUE,
        CREDIT_TYPE,
        DAYS_CREDIT_UPDATE,
        AMT_ANNUITY
    )
    FROM '{DATA_FULL_PATH}/{table_name}.csv' DELIMITER ',' CSV HEADER;
"""

db_manager.send_sql_query(sql_data_query)

Время выполнения: 0:00:07

Вывод данных таблицы из БД

In [ ]:
table_name = "bureau"
sql_query = f"""
    SELECT * FROM {table_name}
    LIMIT 10
"""

df = db_manager.get_df_from_query(sql_query)
df

Время выполнения: 0:00:00

,sk_id_curr,sk_id_bureau,credit_active,credit_currency,days_credit,credit_day_overdue,days_credit_enddate,days_enddate_fact,amt_credit_max_overdue,cnt_credit_prolong,amt_credit_sum,amt_credit_sum_debt,amt_credit_sum_limit,amt_credit_sum_overdue,credit_type,days_credit_update,amt_annuity
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.00,0.00,NaN,0.0,Consumer credit,-131,None
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.00,171342.00,NaN,0.0,Credit card,-20,None
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.50,NaN,NaN,0.0,Consumer credit,-16,None
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.00,NaN,NaN,0.0,Credit card,-16,None
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.00,NaN,NaN,0.0,Consumer credit,-21,None
5,215354,5714467,Active,currency 1,-273,0,27460.0,NaN,0.0,0,180000.00,71017.38,108982.62,0.0,Credit card,-31,None
6,215354,5714468,Active,currency 1,-43,0,79.0,NaN,0.0,0,42103.80,42103.80,0.00,0.0,Consumer credit,-22,None
7,162297,5714469,Closed,currency 1,-1896,0,-1684.0,-1710.0,14985.0,0,76878.45,0.00,0.00,0.0,Consumer credit,-1710,None
8,162297,5714470,Closed,currency 1,-1146,0,-811.0,-840.0,0.0,0,103007.70,0.00,0.00,0.0,Consumer credit,-840,None
9,162297,5714471,Active,currency 1,-1146,0,-484.0,NaN,0.0,0,4500.00,0.00,0.00,0.0,Credit card,-690,None

## Файл bureau_balance.csv

In [47]:
table_name = "bureau_balance"
csv_analyser.analyse_file(f"{table_name}.csv")

Название файла: bureau_balance.csv
Данные: 27299925 строк, 3 столбцов
Столбец SK_ID_BUREAU
- Тип данных: int64
- Уникальных значений: 817395
- Null значений: 0 (0.00%)
- Min: 5001709
- Max: 6842888
Столбец MONTHS_BALANCE
- Описание: Month of balance relative to application date (-1 means the freshest balance date)
- Особенности: time only relative to the application
- Тип данных: int64
- Уникальных значений: 97
- Null значений: 0 (0.00%)
- Min: -96
- Max: 0
Столбец STATUS
- Описание: Status of Credit Bureau loan during the month (active, closed, DPD0-30,… [C means closed, X means status unknown, 0 means no DPD, 1 means maximal did during month between 1-30, 2 means DPD 31-60,… 5 means DPD 120+ or sold or written off ] )
- Тип данных: object
- Уникальных значений: 8
- Null значений: 0 (0.00%)
- Примеры значений: ['C' '0' 'X' '1' '2']

          SK_ID_BUREAU  MONTHS_BALANCE STATUS
0              5715448               0      C
1              5715448              -1      C
2              5715448              -2      C
3              5715448              -3      C
4              5715448              -4      C
...                ...             ...    ...
27299920       5041336             -47      X
27299921       5041336             -48      X
27299922       5041336             -49      X
27299923       5041336             -50      X
27299924       5041336             -51      X

[27299925 rows x 3 columns]

SQL-запрос для создания таблицы

- SK_ID_BUREAU - integer (Стандартный 4-байтовый тип (лимит integer - 2.1 млрд))
- MONTHS_BALANCE - smallint (диапазон от -96 до 0)
- STATUS - char(1) (Минимальный размер для хранения одиночных символов C, X, 0-5)

In [ ]:
table_name = "bureau_balance"
sql_schema_query = f"""
    DROP TABLE IF EXISTS {table_name}; 
    CREATE TABLE {table_name}(
        SK_ID_BUREAU integer,
        MONTHS_BALANCE smallint,
        STATUS char(1)
    )
"""

db_manager.send_sql_query(sql_schema_query)

Время выполнения: 0:00:01

SQL-запрос для заполнения таблицы данными из csv-файла

In [ ]:
table_name = "bureau_balance"
sql_data_query = f"""
    COPY {table_name}(
        SK_ID_BUREAU,
        MONTHS_BALANCE,
        STATUS
    )
    FROM '{DATA_FULL_PATH}/{table_name}.csv' DELIMITER ',' CSV HEADER;
"""

db_manager.send_sql_query(sql_data_query)

Время выполнения: 0:00:22

Вывод данных таблицы из БД

In [ ]:
table_name = "bureau_balance"
sql_query = f"""
    SELECT * FROM {table_name}
    LIMIT 10
"""

df = db_manager.get_df_from_query(sql_query)
df

Время выполнения: 0:00:00

   sk_id_bureau  months_balance status
0       5715448               0      C
1       5715448              -1      C
2       5715448              -2      C
3       5715448              -3      C
4       5715448              -4      C
5       5715448              -5      C
6       5715448              -6      C
7       5715448              -7      C
8       5715448              -8      C
9       5715448              -9      0

## Файл credit_card_balance.csv

In [51]:
table_name = "credit_card_balance"
csv_analyser.analyse_file(f"{table_name}.csv")

Название файла: credit_card_balance.csv
Данные: 3840312 строк, 23 столбцов
Столбец SK_ID_PREV
- Описание: ID of previous credit in Home credit related to loan in our sample. (One loan in our sample can have 0,1,2 or more previous loans in Home Credit)
- Особенности: hashed
- Тип данных: int64
- Уникальных значений: 104307
- Null значений: 0 (0.00%)
- Min: 1000018
- Max: 2843496
Столбец SK_ID_CURR
- Описание: ID of loan in our sample
- Особенности: hashed
- Тип данных: int64
- Уникальных значений: 103558
- Null значений: 0 (0.00%)
- Min: 100006
- Max: 456250
Столбец MONTHS_BALANCE
- Описание: Month of balance relative to application date (-1 means the freshest balance date)
- Особенности: time only relative to the application
- Тип данных: int64
- Уникальных значений: 96
- Null значений: 0 (0.00%)
- Min: -96
- Max: -1
Столбец AMT_BALANCE
- Описание: Balance during the month of previous credit
- Тип данных: float64
- Уникальных значений: 1347904
- Null значений: 0 (0.00%)
- Min: -420250.185
- Max: 1505902.185
Столбец AMT_CREDIT_LIMIT_ACTUAL
- Описание: Credit card limit during the month of the previous credit
- Тип данных: int64
- Уникальных значений: 181
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1350000
Столбец AMT_DRAWINGS_ATM_CURRENT
- Описание: Amount drawing at ATM during the month of the previous credit
- Тип данных: float64
- Уникальных значений: 2267
- Null значений: 749816 (19.52%)
- Min: -6827.31
- Max: 2115000.0
Столбец AMT_DRAWINGS_CURRENT
- Описание: Amount drawing during the month of the previous credit
- Тип данных: float64
- Уникальных значений: 187005
- Null значений: 0 (0.00%)
- Min: -6211.62
- Max: 2287098.315
Столбец AMT_DRAWINGS_OTHER_CURRENT
- Описание: Amount of other drawings during the month of the previous credit
- Тип данных: float64
- Уникальных значений: 1832
- Null значений: 749816 (19.52%)
- Min: 0.0
- Max: 1529847.0
Столбец AMT_DRAWINGS_POS_CURRENT
- Описание: Amount drawing or buying goods during the month of the previous credit
- Тип данных: float64
- Уникальных значений: 168748
- Null значений: 749816 (19.52%)
- Min: 0.0
- Max: 2239274.16
Столбец AMT_INST_MIN_REGULARITY
- Описание: Minimal installment for this month of the previous credit
- Тип данных: float64
- Уникальных значений: 312266
- Null значений: 305236 (7.95%)
- Min: 0.0
- Max: 202882.005
Столбец AMT_PAYMENT_CURRENT
- Описание: How much did the client pay during the month on the previous credit
- Тип данных: float64
- Уникальных значений: 163209
- Null значений: 767988 (20.00%)
- Min: 0.0
- Max: 4289207.445
Столбец AMT_PAYMENT_TOTAL_CURRENT
- Описание: How much did the client pay during the month in total on the previous credit
- Тип данных: float64
- Уникальных значений: 182957
- Null значений: 0 (0.00%)
- Min: 0.0
- Max: 4278315.69
Столбец AMT_RECEIVABLE_PRINCIPAL
- Описание: Amount receivable for principal on the previous credit
- Тип данных: float64
- Уникальных значений: 1195839
- Null значений: 0 (0.00%)
- Min: -423305.82
- Max: 1472316.795
Столбец AMT_RECIVABLE
- Описание: Amount receivable on the previous credit
- Тип данных: float64
- Уникальных значений: 1338878
- Null значений: 0 (0.00%)
- Min: -420250.185
- Max: 1493338.185
Столбец AMT_TOTAL_RECEIVABLE
- Описание: Total amount receivable on the previous credit
- Тип данных: float64
- Уникальных значений: 1339008
- Null значений: 0 (0.00%)
- Min: -420250.185
- Max: 1493338.185
Столбец CNT_DRAWINGS_ATM_CURRENT
- Описание: Number of drawings at ATM during this month on the previous credit
- Тип данных: float64
- Уникальных значений: 44
- Null значений: 749816 (19.52%)
- Min: 0.0
- Max: 51.0
Столбец CNT_DRAWINGS_CURRENT
- Описание: Number of drawings during this month on the previous credit
- Тип данных: int64
- Уникальных значений: 129
- Null значений: 0 (0.00%)
- Min: 0
- Max: 165
Столбец CNT_DRAWINGS_OTHER_CURRENT
- Описание: Number of other drawings during this month on the previous credit
- Тип данных: float64
- Уникальных значений: 11
- Null значений: 749816 (19.52%)
- Min: 0.0
- Max: 12.0
Столбец CNT_DRAWINGS_POS_CURRENT
- Описание: Number of drawings for goods during this month on the previous credit
- Тип данных: float64
- Уникальных значений: 133
- Null значений: 749816 (19.52%)
- Min: 0.0
- Max: 165.0
Столбец CNT_INSTALMENT_MATURE_CUM
- Описание: Number of paid installments on the previous credit
- Тип данных: float64
- Уникальных значений: 121
- Null значений: 305236 (7.95%)
- Min: 0.0
- Max: 120.0
Столбец NAME_CONTRACT_STATUS
- Описание: Contract status (active signed,...) on the previous credit
- Тип данных: object
- Уникальных значений: 7
- Null значений: 0 (0.00%)
- Примеры значений: ['Active' 'Completed' 'Demand' 'Signed' 'Sent proposal']
Столбец SK_DPD
- Описание: DPD (Days past due) during the month on the previous credit
- Тип данных: int64
- Уникальных значений: 917
- Null значений: 0 (0.00%)
- Min: 0
- Max: 3260
Столбец SK_DPD_DEF
- Описание: DPD (Days past due) during the month with tolerance (debts with low loan amounts are ignored) of the previous credit
- Тип данных: int64
- Уникальных значений: 378
- Null значений: 0 (0.00%)
- Min: 0
- Max: 3260

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,2562384,378907,-6,56.970,135000,0.0,877.5,0.0,877.5,1700.325,...,0.000,0.000,0.0,1,0.0,1.0,35.0,Active,0,0
1,2582071,363914,-1,63975.555,45000,2250.0,2250.0,0.0,0.0,2250.000,...,64875.555,64875.555,1.0,1,0.0,0.0,69.0,Active,0,0
2,1740877,371185,-7,31815.225,450000,0.0,0.0,0.0,0.0,2250.000,...,31460.085,31460.085,0.0,0,0.0,0.0,30.0,Active,0,0
3,1389973,337855,-4,236572.110,225000,2250.0,2250.0,0.0,0.0,11795.760,...,233048.970,233048.970,1.0,1,0.0,0.0,10.0,Active,0,0
4,1891521,126868,-1,453919.455,450000,0.0,11547.0,0.0,11547.0,22924.890,...,453919.455,453919.455,0.0,1,0.0,1.0,101.0,Active,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3840307,1036507,328243,-9,0.000,45000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
3840308,1714892,347207,-9,0.000,45000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,23.0,Active,0,0
3840309,1302323,215757,-9,275784.975,585000,270000.0,270000.0,0.0,0.0,2250.000,...,273093.975,273093.975,2.0,2,0.0,0.0,18.0,Active,0,0
3840310,1624872,430337,-10,0.000,450000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
3840311,2411345,236760,-10,0.000,157500,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,21.0,Completed,0,0

SQL-запрос для создания таблицы

- SK_ID_PREV, SK_ID_CURR - integer (Стандартный 4-байтовый тип, значения до 2.8 млн входят в лимит 2.1 млрд)
- MONTHS_BALANCE - smallint (2-байтовый тип, диапазон от -96 до -1 идеально входит в лимит 32767)
- AMT_BALANCE, AMT_DRAWINGS_ATM_CURRENT, AMT_DRAWINGS_CURRENT, AMT_DRAWINGS_OTHER_CURRENT, AMT_DRAWINGS_POS_CURRENT, AMT_INST_MIN_REGULARITY, AMT_PAYMENT_CURRENT, AMT_PAYMENT_TOTAL_CURRENT, AMT_RECEIVABLE_PRINCIPAL, AMT_RECIVABLE, AMT_TOTAL_RECEIVABLE - real (4-байтовый тип для дробных сумм и корректной обработки NULL значений)
- AMT_CREDIT_LIMIT_ACTUAL - integer (Суммы до 1.35 млн без дробной части)
- CNT_DRAWINGS_ATM_CURRENT, CNT_DRAWINGS_OTHER_CURRENT, CNT_DRAWINGS_POS_CURRENT, CNT_INSTALMENT_MATURE_CUM, CNT_DRAWINGS_CURRENT - smallint (счетчики до 165 с дробной частью в файлах)
- NAME_CONTRACT_STATUS - varchar(13) (Максимальная длина строки "Sent proposal" составляет 13 символов)
- SK_DPD, SK_DPD_DEF - smallint (Количество дней просрочки до 3260)

In [ ]:
table_name = "credit_card_balance"
sql_schema_query = f"""
    DROP TABLE IF EXISTS {table_name}; 
    CREATE TABLE {table_name}(
        SK_ID_PREV integer,
        SK_ID_CURR integer,
        MONTHS_BALANCE smallint,
        AMT_BALANCE real,
        AMT_CREDIT_LIMIT_ACTUAL integer,
        AMT_DRAWINGS_ATM_CURRENT real,
        AMT_DRAWINGS_CURRENT real,
        AMT_DRAWINGS_OTHER_CURRENT real,
        AMT_DRAWINGS_POS_CURRENT real,
        AMT_INST_MIN_REGULARITY real,
        AMT_PAYMENT_CURRENT real,
        AMT_PAYMENT_TOTAL_CURRENT real,
        AMT_RECEIVABLE_PRINCIPAL real,
        AMT_RECIVABLE real,
        AMT_TOTAL_RECEIVABLE real,
        CNT_DRAWINGS_ATM_CURRENT real,
        CNT_DRAWINGS_CURRENT real,
        CNT_DRAWINGS_OTHER_CURRENT real,
        CNT_DRAWINGS_POS_CURRENT real,
        CNT_INSTALMENT_MATURE_CUM real,
        NAME_CONTRACT_STATUS varchar(13),
        SK_DPD smallint,
        SK_DPD_DEF smallint
    )
"""

db_manager.send_sql_query(sql_schema_query)

Время выполнения: 0:00:01

SQL-запрос для заполнения таблицы данными из csv-файла

In [ ]:
table_name = "credit_card_balance"
sql_data_query = f"""
    COPY {table_name}(
        SK_ID_PREV,
        SK_ID_CURR,
        MONTHS_BALANCE,
        AMT_BALANCE,
        AMT_CREDIT_LIMIT_ACTUAL,
        AMT_DRAWINGS_ATM_CURRENT,
        AMT_DRAWINGS_CURRENT,
        AMT_DRAWINGS_OTHER_CURRENT,
        AMT_DRAWINGS_POS_CURRENT,
        AMT_INST_MIN_REGULARITY, 
        AMT_PAYMENT_CURRENT,
        AMT_PAYMENT_TOTAL_CURRENT, 
        AMT_RECEIVABLE_PRINCIPAL,
        AMT_RECIVABLE, 
        AMT_TOTAL_RECEIVABLE,
        CNT_DRAWINGS_ATM_CURRENT, 
        CNT_DRAWINGS_CURRENT,
        CNT_DRAWINGS_OTHER_CURRENT, 
        CNT_DRAWINGS_POS_CURRENT,
        CNT_INSTALMENT_MATURE_CUM, 
        NAME_CONTRACT_STATUS,
        SK_DPD,
        SK_DPD_DEF
    )
    FROM '{DATA_FULL_PATH}/{table_name}.csv' DELIMITER ',' CSV HEADER;
"""

db_manager.send_sql_query(sql_data_query)

Время выполнения: 0:00:20

Вывод данных таблицы из БД

In [ ]:
table_name = "credit_card_balance"
sql_query = f"""
    SELECT * FROM {table_name}
    LIMIT 10
"""

df = db_manager.get_df_from_query(sql_query)
df

Время выполнения: 0:00:00

,sk_id_prev,sk_id_curr,months_balance,amt_balance,amt_credit_limit_actual,amt_drawings_atm_current,amt_drawings_current,amt_drawings_other_current,amt_drawings_pos_current,amt_inst_min_regularity,...,amt_recivable,amt_total_receivable,cnt_drawings_atm_current,cnt_drawings_current,cnt_drawings_other_current,cnt_drawings_pos_current,cnt_instalment_mature_cum,name_contract_status,sk_dpd,sk_dpd_def
0,2562384,378907,-6,56.970,135000,0.0,877.50,0.0,877.50,1700.325,...,0.000,0.000,0.0,1.0,0.0,1.0,35.0,Active,0,0
1,2582071,363914,-1,63975.555,45000,2250.0,2250.00,0.0,0.00,2250.000,...,64875.555,64875.555,1.0,1.0,0.0,0.0,69.0,Active,0,0
2,1740877,371185,-7,31815.225,450000,0.0,0.00,0.0,0.00,2250.000,...,31460.086,31460.086,0.0,0.0,0.0,0.0,30.0,Active,0,0
3,1389973,337855,-4,236572.110,225000,2250.0,2250.00,0.0,0.00,11795.760,...,233048.970,233048.970,1.0,1.0,0.0,0.0,10.0,Active,0,0
4,1891521,126868,-1,453919.470,450000,0.0,11547.00,0.0,11547.00,22924.890,...,453919.470,453919.470,0.0,1.0,0.0,1.0,101.0,Active,0,0
5,2646502,380010,-7,82903.810,270000,0.0,0.00,0.0,0.00,4449.105,...,82773.310,82773.310,0.0,0.0,0.0,0.0,2.0,Active,7,0
6,1079071,171320,-6,353451.660,585000,67500.0,67500.00,0.0,0.00,14684.175,...,351881.160,351881.160,1.0,1.0,0.0,0.0,6.0,Active,0,0
7,2095912,118650,-7,47962.125,45000,45000.0,45000.00,0.0,0.00,0.000,...,47962.125,47962.125,1.0,1.0,0.0,0.0,51.0,Active,0,0
8,2181852,367360,-4,291543.060,292500,90000.0,289339.44,0.0,199339.42,130.500,...,286831.560,286831.560,3.0,8.0,0.0,5.0,3.0,Active,0,0
9,1235299,203885,-5,201261.190,225000,76500.0,111026.70,0.0,34526.70,6338.340,...,197224.690,197224.690,3.0,9.0,0.0,6.0,38.0,Active,0,0

## Файл installments_payments.csv

In [55]:
table_name = "installments_payments"
csv_analyser.analyse_file(f"{table_name}.csv")

Название файла: installments_payments.csv
Данные: 13605401 строк, 8 столбцов
Столбец SK_ID_PREV
- Описание: ID of previous credit in Home credit related to loan in our sample. (One loan in our sample can have 0,1,2 or more previous loans in Home Credit)
- Особенности: hashed
- Тип данных: int64
- Уникальных значений: 997752
- Null значений: 0 (0.00%)
- Min: 1000001
- Max: 2843499
Столбец SK_ID_CURR
- Описание: ID of loan in our sample
- Особенности: hashed
- Тип данных: int64
- Уникальных значений: 339587
- Null значений: 0 (0.00%)
- Min: 100001
- Max: 456255
Столбец NUM_INSTALMENT_VERSION
- Описание: Version of installment calendar (0 is for credit card) of previous credit. Change of installment version from month to month signifies that some parameter of payment calendar has changed
- Тип данных: float64
- Уникальных значений: 65
- Null значений: 0 (0.00%)
- Min: 0.0
- Max: 178.0
Столбец NUM_INSTALMENT_NUMBER
- Описание: On which installment we observe payment
- Тип данных: int64
- Уникальных значений: 277
- Null значений: 0 (0.00%)
- Min: 1
- Max: 277
Столбец DAYS_INSTALMENT
- Описание: When the installment of previous credit was supposed to be paid (relative to application date of current loan)
- Особенности: time only relative to the application
- Тип данных: float64
- Уникальных значений: 2922
- Null значений: 0 (0.00%)
- Min: -2922.0
- Max: -1.0
Столбец DAYS_ENTRY_PAYMENT
- Описание: When was the installments of previous credit paid actually (relative to application date of current loan)
- Особенности: time only relative to the application
- Тип данных: float64
- Уникальных значений: 3039
- Null значений: 2905 (0.02%)
- Min: -4921.0
- Max: -1.0
Столбец AMT_INSTALMENT
- Описание: What was the prescribed installment amount of previous credit on this installment
- Тип данных: float64
- Уникальных значений: 902539
- Null значений: 0 (0.00%)
- Min: 0.0
- Max: 3771487.845
Столбец AMT_PAYMENT
- Описание: What the client actually paid on previous credit on this installment
- Тип данных: float64
- Уникальных значений: 944235
- Null значений: 2905 (0.02%)
- Min: 0.0
- Max: 3771487.845

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT
0,1054186,161674,1.0,6,-1180.0,-1187.0,6948.360,6948.360
1,1330831,151639,0.0,34,-2156.0,-2156.0,1716.525,1716.525
2,2085231,193053,2.0,1,-63.0,-63.0,25425.000,25425.000
3,2452527,199697,1.0,3,-2418.0,-2426.0,24350.130,24350.130
4,2714724,167756,1.0,2,-1383.0,-1366.0,2165.040,2160.585
...,...,...,...,...,...,...,...,...
13605396,2186857,428057,0.0,66,-1624.0,NaN,67.500,NaN
13605397,1310347,414406,0.0,47,-1539.0,NaN,67.500,NaN
13605398,1308766,402199,0.0,43,-7.0,NaN,43737.435,NaN
13605399,1062206,409297,0.0,43,-1986.0,NaN,67.500,NaN
13605400,2448869,434321,1.0,19,-27.0,NaN,11504.250,NaN

SQL-запрос для создания таблицы

- SK_ID_PREV, SK_ID_CURR - integer (Стандартный 4-байтовый тип (лимит integer - 2.1 млрд))
- NUM_INSTALMENT_VERSION - real (В CSV значения типа 0.0, 1.0, используем real для обхода ошибок синтаксиса)
- NUM_INSTALMENT_NUMBER - smallint (2-байтовый тип, значения до 277)
- DAYS_INSTALMENT, DAYS_ENTRY_PAYMENT - real (В CSV значения с дробной частью, также присутствуют NULL значения)
- AMT_INSTALMENT, AMT_PAYMENT - real (4-байтовый тип для дробных сумм и корректной обработки NULL значений)

In [ ]:
table_name = "installments_payments"
sql_schema_query = f"""
    DROP TABLE IF EXISTS {table_name}; 
    CREATE TABLE {table_name}(
        SK_ID_PREV integer,
        SK_ID_CURR integer,
        NUM_INSTALMENT_VERSION real,
        NUM_INSTALMENT_NUMBER smallint,
        DAYS_INSTALMENT real,
        DAYS_ENTRY_PAYMENT real,
        AMT_INSTALMENT real,
        AMT_PAYMENT real
    )
"""

db_manager.send_sql_query(sql_schema_query)

Время выполнения: 0:00:00

SQL-запрос для заполнения таблицы данными из csv-файла

In [ ]:
table_name = "installments_payments"
sql_data_query = f"""
    COPY {table_name}(
        SK_ID_PREV,
        SK_ID_CURR,
        NUM_INSTALMENT_VERSION,
        NUM_INSTALMENT_NUMBER,
        DAYS_INSTALMENT,
        DAYS_ENTRY_PAYMENT,
        AMT_INSTALMENT,
        AMT_PAYMENT
    )
    FROM '{DATA_FULL_PATH}/{table_name}.csv' DELIMITER ',' CSV HEADER;
"""

db_manager.send_sql_query(sql_data_query)

Время выполнения: 0:00:32

Вывод данных таблицы из БД

In [ ]:
table_name = "installments_payments"
sql_query = f"""
    SELECT * FROM {table_name}
    LIMIT 10
"""

df = db_manager.get_df_from_query(sql_query)
df

Время выполнения: 0:00:00

,sk_id_prev,sk_id_curr,num_instalment_version,num_instalment_number,days_instalment,days_entry_payment,amt_instalment,amt_payment
0,1054186,161674,1.0,6,-1180.0,-1187.0,6948.360,6948.360
1,1330831,151639,0.0,34,-2156.0,-2156.0,1716.525,1716.525
2,2085231,193053,2.0,1,-63.0,-63.0,25425.000,25425.000
3,2452527,199697,1.0,3,-2418.0,-2426.0,24350.130,24350.130
4,2714724,167756,1.0,2,-1383.0,-1366.0,2165.040,2160.585
5,1137312,164489,1.0,12,-1384.0,-1417.0,5970.375,5970.375
6,2234264,184693,4.0,11,-349.0,-352.0,29432.295,29432.295
7,1818599,111420,2.0,4,-968.0,-994.0,17862.164,17862.164
8,2723183,112102,0.0,14,-197.0,-197.0,70.740,70.740
9,1413990,109741,1.0,4,-570.0,-609.0,14308.470,14308.470

## Файл POS_CASH_balance.csv

In [59]:
table_name = "POS_CASH_balance"
csv_analyser.analyse_file(f"{table_name}.csv")

Название файла: POS_CASH_balance.csv
Данные: 10001358 строк, 8 столбцов
Столбец SK_ID_PREV
- Описание: ID of previous credit in Home Credit related to loan in our sample. (One loan in our sample can have 0,1,2 or more previous loans in Home Credit)
- Тип данных: int64
- Уникальных значений: 936325
- Null значений: 0 (0.00%)
- Min: 1000001
- Max: 2843499
Столбец SK_ID_CURR
- Описание: ID of loan in our sample
- Тип данных: int64
- Уникальных значений: 337252
- Null значений: 0 (0.00%)
- Min: 100001
- Max: 456255
Столбец MONTHS_BALANCE
- Описание: Month of balance relative to application date (-1 means the information to the freshest monthly snapshot, 0 means the information at application - often it will be the same as -1 as many banks are not updating the information to Credit Bureau regularly )
- Особенности: time only relative to the application
- Тип данных: int64
- Уникальных значений: 96
- Null значений: 0 (0.00%)
- Min: -96
- Max: -1
Столбец CNT_INSTALMENT
- Описание: Term of previous credit (can change over time)
- Тип данных: float64
- Уникальных значений: 73
- Null значений: 26071 (0.26%)
- Min: 1.0
- Max: 92.0
Столбец CNT_INSTALMENT_FUTURE
- Описание: Installments left to pay on the previous credit
- Тип данных: float64
- Уникальных значений: 79
- Null значений: 26087 (0.26%)
- Min: 0.0
- Max: 85.0
Столбец NAME_CONTRACT_STATUS
- Описание: Contract status during the month
- Тип данных: object
- Уникальных значений: 9
- Null значений: 0 (0.00%)
- Примеры значений: ['Active' 'Completed' 'Signed' 'Approved' 'Returned to the store']
Столбец SK_DPD
- Описание: DPD (days past due) during the month of previous credit
- Тип данных: int64
- Уникальных значений: 3400
- Null значений: 0 (0.00%)
- Min: 0
- Max: 4231
Столбец SK_DPD_DEF
- Описание: DPD during the month with tolerance (debts with low loan amounts are ignored) of the previous credit
- Тип данных: int64
- Уникальных значений: 2307
- Null значений: 0 (0.00%)
- Min: 0
- Max: 3595

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,1803195,182943,-31,48.0,45.0,Active,0,0
1,1715348,367990,-33,36.0,35.0,Active,0,0
2,1784872,397406,-32,12.0,9.0,Active,0,0
3,1903291,269225,-35,48.0,42.0,Active,0,0
4,2341044,334279,-35,36.0,35.0,Active,0,0
...,...,...,...,...,...,...,...,...
10001353,2448283,226558,-20,6.0,0.0,Active,843,0
10001354,1717234,141565,-19,12.0,0.0,Active,602,0
10001355,1283126,315695,-21,10.0,0.0,Active,609,0
10001356,1082516,450255,-22,12.0,0.0,Active,614,0
10001357,1259607,174278,-52,16.0,0.0,Completed,0,0

SQL-запрос для создания таблицы

- SK_ID_PREV, SK_ID_CURR - integer (Стандартный 4-байтовый тип (лимит integer - 2.1 млрд))
- MONTHS_BALANCE - smallint (диапазон от -96 до -1)
- CNT_INSTALMENT, CNT_INSTALMENT_FUTURE - real (В CSV значения типа 1.0 (с дробной частью), а также есть NULL значения, поэтому real оптимален)
- NAME_CONTRACT_STATUS - varchar(21) (Максимальная длина строки "Returned to the store" составляет 21 символ)
- SK_DPD, SK_DPD_DEF - smallint (Дни просрочки до 4231 с запасом входят в лимит 32767)

In [ ]:
table_name = "POS_CASH_balance"
sql_schema_query = f"""
    DROP TABLE IF EXISTS {table_name}; 
    CREATE TABLE {table_name}(
        SK_ID_PREV integer,
        SK_ID_CURR integer,
        MONTHS_BALANCE smallint,
        CNT_INSTALMENT real,
        CNT_INSTALMENT_FUTURE real,
        NAME_CONTRACT_STATUS varchar(21),
        SK_DPD smallint,
        SK_DPD_DEF smallint
    )
"""

db_manager.send_sql_query(sql_schema_query)

Время выполнения: 0:00:00

SQL-запрос для заполнения таблицы данными из csv-файла

In [ ]:
table_name = "POS_CASH_balance"
sql_data_query = f"""
    COPY {table_name}(
        SK_ID_PREV,
        SK_ID_CURR,
        MONTHS_BALANCE,
        CNT_INSTALMENT,
        CNT_INSTALMENT_FUTURE,
        NAME_CONTRACT_STATUS,
        SK_DPD,
        SK_DPD_DEF
    )
    FROM '{DATA_FULL_PATH}/{table_name}.csv' DELIMITER ',' CSV HEADER;
"""

db_manager.send_sql_query(sql_data_query)

Время выполнения: 0:00:26

Вывод данных таблицы из БД

In [ ]:
table_name = "POS_CASH_balance"
sql_query = f"""
    SELECT * FROM {table_name}
    LIMIT 10
"""

df = db_manager.get_df_from_query(sql_query)
df

Время выполнения: 0:00:00

,sk_id_prev,sk_id_curr,months_balance,cnt_instalment,cnt_instalment_future,name_contract_status,sk_dpd,sk_dpd_def
0,1803195,182943,-31,48.0,45.0,Active,0,0
1,1715348,367990,-33,36.0,35.0,Active,0,0
2,1784872,397406,-32,12.0,9.0,Active,0,0
3,1903291,269225,-35,48.0,42.0,Active,0,0
4,2341044,334279,-35,36.0,35.0,Active,0,0
5,2207092,342166,-32,12.0,12.0,Active,0,0
6,1110516,204376,-38,48.0,43.0,Active,0,0
7,1387235,153211,-35,36.0,36.0,Active,0,0
8,1220500,112740,-31,12.0,12.0,Active,0,0
9,2371489,274851,-32,24.0,16.0,Active,0,0

## Файл previous_application.csv

In [ ]:
table_name = "previous_application"
csv_analyser.analyse_file(f"{table_name}.csv")

Название файла: previous_application.csv
Данные: 1670214 строк, 37 столбцов
Столбец SK_ID_PREV
- Описание: ID of previous credit in Home credit related to loan in our sample. (One loan in our sample can have 0,1,2 or more previous loan applications in Home Credit, previous application could, but not necessarily have to lead to credit)
- Особенности: hashed
- Тип данных: int64
- Уникальных значений: 1670214
- Null значений: 0 (0.00%)
- Min: 1000001
- Max: 2845382
Столбец SK_ID_CURR
- Описание: ID of loan in our sample
- Особенности: hashed
- Тип данных: int64
- Уникальных значений: 338857
- Null значений: 0 (0.00%)
- Min: 100001
- Max: 456255
Столбец NAME_CONTRACT_TYPE
- Описание: Contract product type (Cash loan, consumer loan [POS] ,...) of the previous application
- Тип данных: object
- Уникальных значений: 4
- Null значений: 0 (0.00%)
- Примеры значений: ['Consumer loans' 'Cash loans' 'Revolving loans' 'XNA']
Столбец AMT_ANNUITY
- Описание: Annuity of previous application
- Тип данных: float64
- Уникальных значений: 357959
- Null значений: 372235 (22.29%)
- Min: 0.0
- Max: 418058.145
Столбец AMT_APPLICATION
- Описание: For how much credit did client ask on the previous application
- Тип данных: float64
- Уникальных значений: 93885
- Null значений: 0 (0.00%)
- Min: 0.0
- Max: 6905160.0
Столбец AMT_CREDIT
- Описание: Final credit amount on the previous application. This differs from AMT_APPLICATION in a way that the AMT_APPLICATION is the amount for which the client initially applied for, but during our approval process he could have received different amount - AMT_CREDIT
- Тип данных: float64
- Уникальных значений: 86803
- Null значений: 1 (0.00%)
- Min: 0.0
- Max: 6905160.0
Столбец AMT_DOWN_PAYMENT
- Описание: Down payment on the previous application
- Тип данных: float64
- Уникальных значений: 29278
- Null значений: 895844 (53.64%)
- Min: -0.9
- Max: 3060045.0
Столбец AMT_GOODS_PRICE
- Описание: Goods price of good that client asked for (if applicable) on the previous application
- Тип данных: float64
- Уникальных значений: 93885
- Null значений: 385515 (23.08%)
- Min: 0.0
- Max: 6905160.0
Столбец WEEKDAY_APPR_PROCESS_START
- Описание: On which day of the week did the client apply for previous application
- Тип данных: object
- Уникальных значений: 7
- Null значений: 0 (0.00%)
- Примеры значений: ['SATURDAY' 'THURSDAY' 'TUESDAY' 'MONDAY' 'FRIDAY']
Столбец HOUR_APPR_PROCESS_START
- Описание: Approximately at what day hour did the client apply for the previous application
- Особенности: rounded
- Тип данных: int64
- Уникальных значений: 24
- Null значений: 0 (0.00%)
- Min: 0
- Max: 23
Столбец FLAG_LAST_APPL_PER_CONTRACT
- Описание: Flag if it was last application for the previous contract. Sometimes by mistake of client or our clerk there could be more applications for one single contract
- Тип данных: object
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Примеры значений: ['Y' 'N']
Столбец NFLAG_LAST_APPL_IN_DAY
- Описание: Flag if the application was the last application per day of the client. Sometimes clients apply for more applications a day. Rarely it could also be error in our system that one application is in the database twice
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец RATE_DOWN_PAYMENT
- Описание: Down payment rate normalized on previous credit
- Особенности: normalized
- Тип данных: float64
- Уникальных значений: 207033
- Null значений: 895844 (53.64%)
- Min: -1.4978763414307848e-05
- Max: 1.0
Столбец RATE_INTEREST_PRIMARY
- Описание: Interest rate normalized on previous credit
- Особенности: normalized
- Тип данных: float64
- Уникальных значений: 148
- Null значений: 1664263 (99.64%)
- Min: 0.0347812535418791
- Max: 1.0
Столбец RATE_INTEREST_PRIVILEGED
- Описание: Interest rate normalized on previous credit
- Особенности: normalized
- Тип данных: float64
- Уникальных значений: 25
- Null значений: 1664263 (99.64%)
- Min: 0.3731501057082452
- Max: 1.0
Столбец NAME_CASH_LOAN_PURPOSE
- Описание: Purpose of the cash loan
- Тип данных: object
- Уникальных значений: 25
- Null значений: 0 (0.00%)
- Примеры значений: ['XAP' 'XNA' 'Repairs' 'Everyday expenses' 'Car repairs']
Столбец NAME_CONTRACT_STATUS
- Описание: Contract status (approved, cancelled, ...) of previous application
- Тип данных: object
- Уникальных значений: 4
- Null значений: 0 (0.00%)
- Примеры значений: ['Approved' 'Refused' 'Canceled' 'Unused offer']
Столбец DAYS_DECISION
- Описание: Relative to current application when was the decision about previous application made
- Особенности: time only relative to the application
- Тип данных: int64
- Уникальных значений: 2922
- Null значений: 0 (0.00%)
- Min: -2922
- Max: -1
Столбец NAME_PAYMENT_TYPE
- Описание: Payment method that client chose to pay for the previous application
- Тип данных: object
- Уникальных значений: 4
- Null значений: 0 (0.00%)
- Примеры значений: ['Cash through the bank' 'XNA' 'Non-cash from your account'
 'Cashless from the account of the employer']
Столбец CODE_REJECT_REASON
- Описание: Why was the previous application rejected
- Тип данных: object
- Уникальных значений: 9
- Null значений: 0 (0.00%)
- Примеры значений: ['XAP' 'HC' 'LIMIT' 'CLIENT' 'SCOFR']
Столбец NAME_TYPE_SUITE
- Описание: Who accompanied client when applying for the previous application
- Тип данных: object
- Уникальных значений: 7
- Null значений: 820405 (49.12%)
- Примеры значений: ['Unaccompanied' 'Spouse, partner' 'Family' 'Children' 'Other_B']
Столбец NAME_CLIENT_TYPE
- Описание: Was the client old or new client when applying for the previous application
- Тип данных: object
- Уникальных значений: 4
- Null значений: 0 (0.00%)
- Примеры значений: ['Repeater' 'New' 'Refreshed' 'XNA']
Столбец NAME_GOODS_CATEGORY
- Описание: What kind of goods did the client apply for in the previous application
- Тип данных: object
- Уникальных значений: 28
- Null значений: 0 (0.00%)
- Примеры значений: ['Mobile' 'XNA' 'Consumer Electronics' 'Construction Materials'
 'Auto Accessories']
Столбец NAME_PORTFOLIO
- Описание: Was the previous application for CASH, POS, CAR, …
- Тип данных: object
- Уникальных значений: 5
- Null значений: 0 (0.00%)
- Примеры значений: ['POS' 'Cash' 'XNA' 'Cards' 'Cars']
Столбец NAME_PRODUCT_TYPE
- Описание: Was the previous application x-sell o walk-in
- Тип данных: object
- Уникальных значений: 3
- Null значений: 0 (0.00%)
- Примеры значений: ['XNA' 'x-sell' 'walk-in']
Столбец CHANNEL_TYPE
- Описание: Through which channel we acquired the client on the previous application
- Тип данных: object
- Уникальных значений: 8
- Null значений: 0 (0.00%)
- Примеры значений: ['Country-wide' 'Contact center' 'Credit and cash offices' 'Stone'
 'Regional / Local']
Столбец SELLERPLACE_AREA
- Описание: Selling area of seller place of the previous application
- Тип данных: int64
- Уникальных значений: 2097
- Null значений: 0 (0.00%)
- Min: -1
- Max: 4000000
Столбец NAME_SELLER_INDUSTRY
- Описание: The industry of the seller
- Тип данных: object
- Уникальных значений: 11
- Null значений: 0 (0.00%)
- Примеры значений: ['Connectivity' 'XNA' 'Consumer electronics' 'Industry' 'Clothing']
Столбец CNT_PAYMENT
- Описание: Term of previous credit at application of the previous application
- Тип данных: float64
- Уникальных значений: 49
- Null значений: 372230 (22.29%)
- Min: 0.0
- Max: 84.0
Столбец NAME_YIELD_GROUP
- Описание: Grouped interest rate into small medium and high of the previous application
- Особенности: grouped
- Тип данных: object
- Уникальных значений: 5
- Null значений: 0 (0.00%)
- Примеры значений: ['middle' 'low_action' 'high' 'low_normal' 'XNA']
Столбец PRODUCT_COMBINATION
- Описание: Detailed product combination of the previous application
- Тип данных: object
- Уникальных значений: 17
- Null значений: 346 (0.02%)
- Примеры значений: ['POS mobile with interest' 'Cash X-Sell: low' 'Cash X-Sell: high'
 'Cash X-Sell: middle' 'Cash Street: high']
Столбец DAYS_FIRST_DRAWING
- Описание: Relative to application date of current application when was the first disbursement of the previous application
- Особенности: time only relative to the application
- Тип данных: float64
- Уникальных значений: 2838
- Null значений: 673065 (40.30%)
- Min: -2922.0
- Max: 365243.0
Столбец DAYS_FIRST_DUE
- Описание: Relative to application date of current application when was the first due supposed to be of the previous application
- Особенности: time only relative to the application
- Тип данных: float64
- Уникальных значений: 2892
- Null значений: 673065 (40.30%)
- Min: -2892.0
- Max: 365243.0
Столбец DAYS_LAST_DUE_1ST_VERSION
- Описание: Relative to application date of current application when was the first due of the previous application
- Особенности: time only relative to the application
- Тип данных: float64
- Уникальных значений: 4605
- Null значений: 673065 (40.30%)
- Min: -2801.0
- Max: 365243.0
Столбец DAYS_LAST_DUE
- Описание: Relative to application date of current application when was the first due of the previous application
- Особенности: time only relative to the application
- Тип данных: float64
- Уникальных значений: 2873
- Null значений: 673065 (40.30%)
- Min: -2889.0
- Max: 365243.0
Столбец DAYS_TERMINATION
- Описание: Relative to application date of current application when was the expected termination of the previous application
- Особенности: time only relative to the application
- Тип данных: float64
- Уникальных значений: 2830
- Null значений: 673065 (40.30%)
- Min: -2874.0
- Max: 365243.0
Столбец NFLAG_INSURED_ON_APPROVAL
- Описание: Did the client requested insurance during the previous application
- Тип данных: float64
- Уникальных значений: 2
- Null значений: 673065 (40.30%)
- Min: 0.0
- Max: 1.0

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1670209,2300464,352015,Consumer loans,14704.290,267295.5,311400.0,0.0,267295.5,WEDNESDAY,12,...,Furniture,30.0,low_normal,POS industry with interest,365243.0,-508.0,362.0,-358.0,-351.0,0.0
1670210,2357031,334635,Consumer loans,6622.020,87750.0,64291.5,29250.0,87750.0,TUESDAY,15,...,Furniture,12.0,middle,POS industry with interest,365243.0,-1604.0,-1274.0,-1304.0,-1297.0,0.0
1670211,2659632,249544,Consumer loans,11520.855,105237.0,102523.5,10525.5,105237.0,MONDAY,12,...,Consumer electronics,10.0,low_normal,POS household with interest,365243.0,-1457.0,-1187.0,-1187.0,-1181.0,0.0
1670212,2785582,400317,Cash loans,18821.520,180000.0,191880.0,NaN,180000.0,WEDNESDAY,9,...,XNA,12.0,low_normal,Cash X-Sell: low,365243.0,-1155.0,-825.0,-825.0,-817.0,1.0
1670213,2418762,261212,Cash loans,16431.300,360000.0,360000.0,NaN,360000.0,SUNDAY,10,...,XNA,48.0,middle,Cash X-Sell: middle,365243.0,-1163.0,247.0,-443.0,-423.0,0.0

SQL-запрос для создания таблицы

- SK_ID_PREV, SK_ID_CURR - integer (значения до 2.8 млн)
- NAME_CONTRACT_TYPE, NAME_CASH_LOAN_PURPOSE, NAME_CONTRACT_STATUS, NAME_PAYMENT_TYPE, CODE_REJECT_REASON, NAME_CLIENT_TYPE, NAME_GOODS_CATEGORY, NAME_PORTFOLIO, NAME_PRODUCT_TYPE, CHANNEL_TYPE, NAME_SELLER_INDUSTRY, NAME_YIELD_GROUP, PRODUCT_COMBINATION - varchar (Размер от 10 до 50 символов в зависимости от максимальной длины значения в столбце)
- AMT_ANNUITY, AMT_APPLICATION, AMT_CREDIT, AMT_DOWN_PAYMENT, AMT_GOODS_PRICE, RATE_DOWN_PAYMENT, RATE_INTEREST_PRIMARY, RATE_INTEREST_PRIVILEGED - real (4-байтовый тип для дробных значений и поддержки NULL)
- WEEKDAY_APPR_PROCESS_START - varchar(9) (Максимальная длина для "WEDNESDAY")
- HOUR_APPR_PROCESS_START, NFLAG_LAST_APPL_IN_DAY, DAYS_DECISION, SELLERPLACE_AREA - integer (Целочисленные значения, SELLERPLACE_AREA до 4 млн)
- FLAG_LAST_APPL_PER_CONTRACT - char(1) (Для флагов Y/N)
- CNT_PAYMENT, DAYS_FIRST_DRAWING, DAYS_FIRST_DUE, DAYS_LAST_DUE_1ST_VERSION, DAYS_LAST_DUE, DAYS_TERMINATION, NFLAG_INSURED_ON_APPROVAL - real (В CSV значения с точкой типа 365243.0 и много NULL)
- NAME_TYPE_SUITE - varchar(15) (Максимальная длина для "Unaccompanied")

In [ ]:
table_name = "previous_application"
sql_schema_query = f"""
    DROP TABLE IF EXISTS {table_name}; 
    CREATE TABLE {table_name}(
        SK_ID_PREV integer,
        SK_ID_CURR integer,
        NAME_CONTRACT_TYPE varchar(15),
        AMT_ANNUITY real,
        AMT_APPLICATION real,
        AMT_CREDIT real,
        AMT_DOWN_PAYMENT real,
        AMT_GOODS_PRICE real,
        WEEKDAY_APPR_PROCESS_START varchar(9),
        HOUR_APPR_PROCESS_START integer,
        FLAG_LAST_APPL_PER_CONTRACT char(1),
        NFLAG_LAST_APPL_IN_DAY integer,
        RATE_DOWN_PAYMENT real,
        RATE_INTEREST_PRIMARY real,
        RATE_INTEREST_PRIVILEGED real,
        NAME_CASH_LOAN_PURPOSE varchar(34),
        NAME_CONTRACT_STATUS varchar(15),
        DAYS_DECISION integer,
        NAME_PAYMENT_TYPE varchar(50),
        CODE_REJECT_REASON varchar(9),
        NAME_TYPE_SUITE varchar(15),
        NAME_CLIENT_TYPE varchar(10),
        NAME_GOODS_CATEGORY varchar(25),
        NAME_PORTFOLIO varchar(10),
        NAME_PRODUCT_TYPE varchar(10),
        CHANNEL_TYPE varchar(30),
        SELLERPLACE_AREA integer,
        NAME_SELLER_INDUSTRY varchar(25),
        CNT_PAYMENT real,
        NAME_YIELD_GROUP varchar(15),
        PRODUCT_COMBINATION varchar(34),
        DAYS_FIRST_DRAWING real,
        DAYS_FIRST_DUE real,
        DAYS_LAST_DUE_1ST_VERSION real,
        DAYS_LAST_DUE real,
        DAYS_TERMINATION real,
        NFLAG_INSURED_ON_APPROVAL real
    )
"""

db_manager.send_sql_query(sql_schema_query)

Время выполнения: 0:00:00

SQL-запрос для заполнения таблицы данными из csv-файла

In [ ]:
table_name = "previous_application"
sql_data_query = f"""
    COPY {table_name}(
        SK_ID_PREV,
        SK_ID_CURR,
        NAME_CONTRACT_TYPE,
        AMT_ANNUITY,
        AMT_APPLICATION,
        AMT_CREDIT,
        AMT_DOWN_PAYMENT,
        AMT_GOODS_PRICE,
        WEEKDAY_APPR_PROCESS_START,
        HOUR_APPR_PROCESS_START,
        FLAG_LAST_APPL_PER_CONTRACT,
        NFLAG_LAST_APPL_IN_DAY,
        RATE_DOWN_PAYMENT,
        RATE_INTEREST_PRIMARY,
        RATE_INTEREST_PRIVILEGED,
        NAME_CASH_LOAN_PURPOSE,
        NAME_CONTRACT_STATUS,
        DAYS_DECISION,
        NAME_PAYMENT_TYPE,
        CODE_REJECT_REASON,
        NAME_TYPE_SUITE,
        NAME_CLIENT_TYPE,
        NAME_GOODS_CATEGORY,
        NAME_PORTFOLIO,
        NAME_PRODUCT_TYPE,
        CHANNEL_TYPE,
        SELLERPLACE_AREA,
        NAME_SELLER_INDUSTRY,
        CNT_PAYMENT,
        NAME_YIELD_GROUP,
        PRODUCT_COMBINATION,
        DAYS_FIRST_DRAWING,
        DAYS_FIRST_DUE,
        DAYS_LAST_DUE_1ST_VERSION,
        DAYS_LAST_DUE,
        DAYS_TERMINATION,
        NFLAG_INSURED_ON_APPROVAL
    )
    FROM '{DATA_FULL_PATH}/{table_name}.csv' DELIMITER ',' CSV HEADER;
"""

db_manager.send_sql_query(sql_data_query)

Время выполнения: 0:00:13

Вывод данных таблицы из БД

In [ ]:
table_name = "previous_application"
sql_query = f"""
    SELECT * FROM {table_name}
    LIMIT 10
"""

df = db_manager.get_df_from_query(sql_query)
df

Время выполнения: 0:00:00

,sk_id_prev,sk_id_curr,name_contract_type,amt_annuity,amt_application,amt_credit,amt_down_payment,amt_goods_price,weekday_appr_process_start,hour_appr_process_start,...,name_seller_industry,cnt_payment,name_yield_group,product_combination,days_first_drawing,days_first_due,days_last_due_1st_version,days_last_due,days_termination,nflag_insured_on_approval
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.336,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN
5,1383531,199383,Cash loans,23703.930,315000.0,340573.5,NaN,315000.0,SATURDAY,8,...,XNA,18.0,low_normal,Cash X-Sell: low,365243.0,-654.0,-144.0,-144.0,-137.0,1.0
6,2315218,175704,Cash loans,NaN,0.0,0.0,NaN,NaN,TUESDAY,11,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
7,1656711,296299,Cash loans,NaN,0.0,0.0,NaN,NaN,MONDAY,7,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
8,2367563,342292,Cash loans,NaN,0.0,0.0,NaN,NaN,MONDAY,15,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
9,2579447,334349,Cash loans,NaN,0.0,0.0,NaN,NaN,SATURDAY,15,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN

## Файлы application_test.csv и application_train.csv

In [67]:
table_name = "application"
csv_analyser.analyse_file(f"{table_name}_train.csv")

Название файла: application_train.csv
Данные: 307511 строк, 122 столбцов
Столбец SK_ID_CURR
- Тип данных: int64
- Уникальных значений: 307511
- Null значений: 0 (0.00%)
- Min: 100002
- Max: 456255
Столбец TARGET
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец NAME_CONTRACT_TYPE
- Тип данных: object
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Примеры значений: ['Cash loans' 'Revolving loans']
Столбец CODE_GENDER
- Тип данных: object
- Уникальных значений: 3
- Null значений: 0 (0.00%)
- Примеры значений: ['M' 'F' 'XNA']
Столбец FLAG_OWN_CAR
- Тип данных: object
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Примеры значений: ['N' 'Y']
Столбец FLAG_OWN_REALTY
- Тип данных: object
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Примеры значений: ['Y' 'N']
Столбец CNT_CHILDREN
- Тип данных: int64
- Уникальных значений: 15
- Null значений: 0 (0.00%)
- Min: 0
- Max: 19
Столбец AMT_INCOME_TOTAL
- Тип данных: float64
- Уникальных значений: 2548
- Null значений: 0 (0.00%)
- Min: 25650.0
- Max: 117000000.0
Столбец AMT_CREDIT
- Тип данных: float64
- Уникальных значений: 5603
- Null значений: 0 (0.00%)
- Min: 45000.0
- Max: 4050000.0
Столбец AMT_ANNUITY
- Тип данных: float64
- Уникальных значений: 13672
- Null значений: 12 (0.00%)
- Min: 1615.5
- Max: 258025.5
Столбец AMT_GOODS_PRICE
- Тип данных: float64
- Уникальных значений: 1002
- Null значений: 278 (0.09%)
- Min: 40500.0
- Max: 4050000.0
Столбец NAME_TYPE_SUITE
- Тип данных: object
- Уникальных значений: 7
- Null значений: 1292 (0.42%)
- Примеры значений: ['Unaccompanied' 'Family' 'Spouse, partner' 'Children' 'Other_A']
Столбец NAME_INCOME_TYPE
- Тип данных: object
- Уникальных значений: 8
- Null значений: 0 (0.00%)
- Примеры значений: ['Working' 'State servant' 'Commercial associate' 'Pensioner' 'Unemployed']
Столбец NAME_EDUCATION_TYPE
- Тип данных: object
- Уникальных значений: 5
- Null значений: 0 (0.00%)
- Примеры значений: ['Secondary / secondary special' 'Higher education' 'Incomplete higher'
 'Lower secondary' 'Academic degree']
Столбец NAME_FAMILY_STATUS
- Тип данных: object
- Уникальных значений: 6
- Null значений: 0 (0.00%)
- Примеры значений: ['Single / not married' 'Married' 'Civil marriage' 'Widow' 'Separated']
Столбец NAME_HOUSING_TYPE
- Тип данных: object
- Уникальных значений: 6
- Null значений: 0 (0.00%)
- Примеры значений: ['House / apartment' 'Rented apartment' 'With parents'
 'Municipal apartment' 'Office apartment']
Столбец REGION_POPULATION_RELATIVE
- Тип данных: float64
- Уникальных значений: 81
- Null значений: 0 (0.00%)
- Min: 0.00029
- Max: 0.072508
Столбец DAYS_BIRTH
- Тип данных: int64
- Уникальных значений: 17460
- Null значений: 0 (0.00%)
- Min: -25229
- Max: -7489
Столбец DAYS_EMPLOYED
- Тип данных: int64
- Уникальных значений: 12574
- Null значений: 0 (0.00%)
- Min: -17912
- Max: 365243
Столбец DAYS_REGISTRATION
- Тип данных: float64
- Уникальных значений: 15688
- Null значений: 0 (0.00%)
- Min: -24672.0
- Max: 0.0
Столбец DAYS_ID_PUBLISH
- Тип данных: int64
- Уникальных значений: 6168
- Null значений: 0 (0.00%)
- Min: -7197
- Max: 0
Столбец OWN_CAR_AGE
- Тип данных: float64
- Уникальных значений: 62
- Null значений: 202929 (65.99%)
- Min: 0.0
- Max: 91.0
Столбец FLAG_MOBIL
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец FLAG_EMP_PHONE
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец FLAG_WORK_PHONE
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец FLAG_CONT_MOBILE
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец FLAG_PHONE
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец FLAG_EMAIL
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец OCCUPATION_TYPE
- Тип данных: object
- Уникальных значений: 18
- Null значений: 96391 (31.35%)
- Примеры значений: ['Laborers' 'Core staff' 'Accountants' 'Managers' 'Drivers']
Столбец CNT_FAM_MEMBERS
- Тип данных: float64
- Уникальных значений: 17
- Null значений: 2 (0.00%)
- Min: 1.0
- Max: 20.0
Столбец REGION_RATING_CLIENT
- Тип данных: int64
- Уникальных значений: 3
- Null значений: 0 (0.00%)
- Min: 1
- Max: 3
Столбец REGION_RATING_CLIENT_W_CITY
- Тип данных: int64
- Уникальных значений: 3
- Null значений: 0 (0.00%)
- Min: 1
- Max: 3
Столбец WEEKDAY_APPR_PROCESS_START
- Тип данных: object
- Уникальных значений: 7
- Null значений: 0 (0.00%)
- Примеры значений: ['WEDNESDAY' 'MONDAY' 'THURSDAY' 'SUNDAY' 'SATURDAY']
Столбец HOUR_APPR_PROCESS_START
- Тип данных: int64
- Уникальных значений: 24
- Null значений: 0 (0.00%)
- Min: 0
- Max: 23
Столбец REG_REGION_NOT_LIVE_REGION
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец REG_REGION_NOT_WORK_REGION
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец LIVE_REGION_NOT_WORK_REGION
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец REG_CITY_NOT_LIVE_CITY
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец REG_CITY_NOT_WORK_CITY
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец LIVE_CITY_NOT_WORK_CITY
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец ORGANIZATION_TYPE
- Тип данных: object
- Уникальных значений: 58
- Null значений: 0 (0.00%)
- Примеры значений: ['Business Entity Type 3' 'School' 'Government' 'Religion' 'Other']
Столбец EXT_SOURCE_1
- Тип данных: float64
- Уникальных значений: 114584
- Null значений: 173378 (56.38%)
- Min: 0.0145681324124455
- Max: 0.962692770561306
Столбец EXT_SOURCE_2
- Тип данных: float64
- Уникальных значений: 119831
- Null значений: 660 (0.21%)
- Min: 8.173616518884397e-08
- Max: 0.8549996664047012
Столбец EXT_SOURCE_3
- Тип данных: float64
- Уникальных значений: 814
- Null значений: 60965 (19.83%)
- Min: 0.0005272652387098
- Max: 0.8960095494948396
Столбец APARTMENTS_AVG
- Тип данных: float64
- Уникальных значений: 2339
- Null значений: 156061 (50.75%)
- Min: 0.0
- Max: 1.0
Столбец BASEMENTAREA_AVG
- Тип данных: float64
- Уникальных значений: 3780
- Null значений: 179943 (58.52%)
- Min: 0.0
- Max: 1.0
Столбец YEARS_BEGINEXPLUATATION_AVG
- Тип данных: float64
- Уникальных значений: 285
- Null значений: 150007 (48.78%)
- Min: 0.0
- Max: 1.0
Столбец YEARS_BUILD_AVG
- Тип данных: float64
- Уникальных значений: 149
- Null значений: 204488 (66.50%)
- Min: 0.0
- Max: 1.0
Столбец COMMONAREA_AVG
- Тип данных: float64
- Уникальных значений: 3181
- Null значений: 214865 (69.87%)
- Min: 0.0
- Max: 1.0
Столбец ELEVATORS_AVG
- Тип данных: float64
- Уникальных значений: 257
- Null значений: 163891 (53.30%)
- Min: 0.0
- Max: 1.0
Столбец ENTRANCES_AVG
- Тип данных: float64
- Уникальных значений: 285
- Null значений: 154828 (50.35%)
- Min: 0.0
- Max: 1.0
Столбец FLOORSMAX_AVG
- Тип данных: float64
- Уникальных значений: 403
- Null значений: 153020 (49.76%)
- Min: 0.0
- Max: 1.0
Столбец FLOORSMIN_AVG
- Тип данных: float64
- Уникальных значений: 305
- Null значений: 208642 (67.85%)
- Min: 0.0
- Max: 1.0
Столбец LANDAREA_AVG
- Тип данных: float64
- Уникальных значений: 3527
- Null значений: 182590 (59.38%)
- Min: 0.0
- Max: 1.0
Столбец LIVINGAPARTMENTS_AVG
- Тип данных: float64
- Уникальных значений: 1868
- Null значений: 210199 (68.35%)
- Min: 0.0
- Max: 1.0
Столбец LIVINGAREA_AVG
- Тип данных: float64
- Уникальных значений: 5199
- Null значений: 154350 (50.19%)
- Min: 0.0
- Max: 1.0
Столбец NONLIVINGAPARTMENTS_AVG
- Тип данных: float64
- Уникальных значений: 386
- Null значений: 213514 (69.43%)
- Min: 0.0
- Max: 1.0
Столбец NONLIVINGAREA_AVG
- Тип данных: float64
- Уникальных значений: 3290
- Null значений: 169682 (55.18%)
- Min: 0.0
- Max: 1.0
Столбец APARTMENTS_MODE
- Тип данных: float64
- Уникальных значений: 760
- Null значений: 156061 (50.75%)
- Min: 0.0
- Max: 1.0
Столбец BASEMENTAREA_MODE
- Тип данных: float64
- Уникальных значений: 3841
- Null значений: 179943 (58.52%)
- Min: 0.0
- Max: 1.0
Столбец YEARS_BEGINEXPLUATATION_MODE
- Тип данных: float64
- Уникальных значений: 221
- Null значений: 150007 (48.78%)
- Min: 0.0
- Max: 1.0
Столбец YEARS_BUILD_MODE
- Тип данных: float64
- Уникальных значений: 154
- Null значений: 204488 (66.50%)
- Min: 0.0
- Max: 1.0
Столбец COMMONAREA_MODE
- Тип данных: float64
- Уникальных значений: 3128
- Null значений: 214865 (69.87%)
- Min: 0.0
- Max: 1.0
Столбец ELEVATORS_MODE
- Тип данных: float64
- Уникальных значений: 26
- Null значений: 163891 (53.30%)
- Min: 0.0
- Max: 1.0
Столбец ENTRANCES_MODE
- Тип данных: float64
- Уникальных значений: 30
- Null значений: 154828 (50.35%)
- Min: 0.0
- Max: 1.0
Столбец FLOORSMAX_MODE
- Тип данных: float64
- Уникальных значений: 25
- Null значений: 153020 (49.76%)
- Min: 0.0
- Max: 1.0
Столбец FLOORSMIN_MODE
- Тип данных: float64
- Уникальных значений: 25
- Null значений: 208642 (67.85%)
- Min: 0.0
- Max: 1.0
Столбец LANDAREA_MODE
- Тип данных: float64
- Уникальных значений: 3563
- Null значений: 182590 (59.38%)
- Min: 0.0
- Max: 1.0
Столбец LIVINGAPARTMENTS_MODE
- Тип данных: float64
- Уникальных значений: 736
- Null значений: 210199 (68.35%)
- Min: 0.0
- Max: 1.0
Столбец LIVINGAREA_MODE
- Тип данных: float64
- Уникальных значений: 5301
- Null значений: 154350 (50.19%)
- Min: 0.0
- Max: 1.0
Столбец NONLIVINGAPARTMENTS_MODE
- Тип данных: float64
- Уникальных значений: 167
- Null значений: 213514 (69.43%)
- Min: 0.0
- Max: 1.0
Столбец NONLIVINGAREA_MODE
- Тип данных: float64
- Уникальных значений: 3327
- Null значений: 169682 (55.18%)
- Min: 0.0
- Max: 1.0
Столбец APARTMENTS_MEDI
- Тип данных: float64
- Уникальных значений: 1148
- Null значений: 156061 (50.75%)
- Min: 0.0
- Max: 1.0
Столбец BASEMENTAREA_MEDI
- Тип данных: float64
- Уникальных значений: 3772
- Null значений: 179943 (58.52%)
- Min: 0.0
- Max: 1.0
Столбец YEARS_BEGINEXPLUATATION_MEDI
- Тип данных: float64
- Уникальных значений: 245
- Null значений: 150007 (48.78%)
- Min: 0.0
- Max: 1.0
Столбец YEARS_BUILD_MEDI
- Тип данных: float64
- Уникальных значений: 151
- Null значений: 204488 (66.50%)
- Min: 0.0
- Max: 1.0
Столбец COMMONAREA_MEDI
- Тип данных: float64
- Уникальных значений: 3202
- Null значений: 214865 (69.87%)
- Min: 0.0
- Max: 1.0
Столбец ELEVATORS_MEDI
- Тип данных: float64
- Уникальных значений: 46
- Null значений: 163891 (53.30%)
- Min: 0.0
- Max: 1.0
Столбец ENTRANCES_MEDI
- Тип данных: float64
- Уникальных значений: 46
- Null значений: 154828 (50.35%)
- Min: 0.0
- Max: 1.0
Столбец FLOORSMAX_MEDI
- Тип данных: float64
- Уникальных значений: 49
- Null значений: 153020 (49.76%)
- Min: 0.0
- Max: 1.0
Столбец FLOORSMIN_MEDI
- Тип данных: float64
- Уникальных значений: 47
- Null значений: 208642 (67.85%)
- Min: 0.0
- Max: 1.0
Столбец LANDAREA_MEDI
- Тип данных: float64
- Уникальных значений: 3560
- Null значений: 182590 (59.38%)
- Min: 0.0
- Max: 1.0
Столбец LIVINGAPARTMENTS_MEDI
- Тип данных: float64
- Уникальных значений: 1097
- Null значений: 210199 (68.35%)
- Min: 0.0
- Max: 1.0
Столбец LIVINGAREA_MEDI
- Тип данных: float64
- Уникальных значений: 5281
- Null значений: 154350 (50.19%)
- Min: 0.0
- Max: 1.0
Столбец NONLIVINGAPARTMENTS_MEDI
- Тип данных: float64
- Уникальных значений: 214
- Null значений: 213514 (69.43%)
- Min: 0.0
- Max: 1.0
Столбец NONLIVINGAREA_MEDI
- Тип данных: float64
- Уникальных значений: 3323
- Null значений: 169682 (55.18%)
- Min: 0.0
- Max: 1.0
Столбец FONDKAPREMONT_MODE
- Тип данных: object
- Уникальных значений: 4
- Null значений: 210295 (68.39%)
- Примеры значений: ['reg oper account' 'org spec account' 'reg oper spec account'
 'not specified']
Столбец HOUSETYPE_MODE
- Тип данных: object
- Уникальных значений: 3
- Null значений: 154297 (50.18%)
- Примеры значений: ['block of flats' 'terraced house' 'specific housing']
Столбец TOTALAREA_MODE
- Тип данных: float64
- Уникальных значений: 5116
- Null значений: 148431 (48.27%)
- Min: 0.0
- Max: 1.0
Столбец WALLSMATERIAL_MODE
- Тип данных: object
- Уникальных значений: 7
- Null значений: 156341 (50.84%)
- Примеры значений: ['Stone, brick' 'Block' 'Panel' 'Mixed' 'Wooden']
Столбец EMERGENCYSTATE_MODE
- Тип данных: object
- Уникальных значений: 2
- Null значений: 145755 (47.40%)
- Примеры значений: ['No' 'Yes']
Столбец OBS_30_CNT_SOCIAL_CIRCLE
- Тип данных: float64
- Уникальных значений: 33
- Null значений: 1021 (0.33%)
- Min: 0.0
- Max: 348.0
Столбец DEF_30_CNT_SOCIAL_CIRCLE
- Тип данных: float64
- Уникальных значений: 10
- Null значений: 1021 (0.33%)
- Min: 0.0
- Max: 34.0
Столбец OBS_60_CNT_SOCIAL_CIRCLE
- Тип данных: float64
- Уникальных значений: 33
- Null значений: 1021 (0.33%)
- Min: 0.0
- Max: 344.0
Столбец DEF_60_CNT_SOCIAL_CIRCLE
- Тип данных: float64
- Уникальных значений: 9
- Null значений: 1021 (0.33%)
- Min: 0.0
- Max: 24.0
Столбец DAYS_LAST_PHONE_CHANGE
- Тип данных: float64
- Уникальных значений: 3773
- Null значений: 1 (0.00%)
- Min: -4292.0
- Max: 0.0
Столбец FLAG_DOCUMENT_2
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец FLAG_DOCUMENT_3
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец FLAG_DOCUMENT_4
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец FLAG_DOCUMENT_5
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец FLAG_DOCUMENT_6
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец FLAG_DOCUMENT_7
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец FLAG_DOCUMENT_8
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец FLAG_DOCUMENT_9
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец FLAG_DOCUMENT_10
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец FLAG_DOCUMENT_11
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец FLAG_DOCUMENT_12
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец FLAG_DOCUMENT_13
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец FLAG_DOCUMENT_14
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец FLAG_DOCUMENT_15
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец FLAG_DOCUMENT_16
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец FLAG_DOCUMENT_17
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец FLAG_DOCUMENT_18
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец FLAG_DOCUMENT_19
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец FLAG_DOCUMENT_20
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец FLAG_DOCUMENT_21
- Тип данных: int64
- Уникальных значений: 2
- Null значений: 0 (0.00%)
- Min: 0
- Max: 1
Столбец AMT_REQ_CREDIT_BUREAU_HOUR
- Тип данных: float64
- Уникальных значений: 5
- Null значений: 41519 (13.50%)
- Min: 0.0
- Max: 4.0
Столбец AMT_REQ_CREDIT_BUREAU_DAY
- Тип данных: float64
- Уникальных значений: 9
- Null значений: 41519 (13.50%)
- Min: 0.0
- Max: 9.0
Столбец AMT_REQ_CREDIT_BUREAU_WEEK
- Тип данных: float64
- Уникальных значений: 9
- Null значений: 41519 (13.50%)
- Min: 0.0
- Max: 8.0
Столбец AMT_REQ_CREDIT_BUREAU_MON
- Тип данных: float64
- Уникальных значений: 24
- Null значений: 41519 (13.50%)
- Min: 0.0
- Max: 27.0
Столбец AMT_REQ_CREDIT_BUREAU_QRT
- Тип данных: float64
- Уникальных значений: 11
- Null значений: 41519 (13.50%)
- Min: 0.0
- Max: 261.0
Столбец AMT_REQ_CREDIT_BUREAU_YEAR
- Тип данных: float64
- Уникальных значений: 25
- Null значений: 41519 (13.50%)
- Min: 0.0
- Max: 25.0

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307507,456252,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307508,456253,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,...,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0
307509,456254,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307510,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0

SQL-запрос для создания таблицы

- SK_ID_CURR - integer (лимит 2.1 млрд)
- NAME_CONTRACT_TYPE, NAME_TYPE_SUITE, NAME_INCOME_TYPE, NAME_EDUCATION_TYPE, NAME_FAMILY_STATUS, NAME_HOUSING_TYPE, OCCUPATION_TYPE, WEEKDAY_APPR_PROCESS_START, ORGANIZATION_TYPE, FONDKAPREMONT_MODE, HOUSETYPE_MODE, WALLSMATERIAL_MODE - varchar (Размер от 10 до 60 символов, ORGANIZATION_TYPE - самый длинный до 60)
- CODE_GENDER, FLAG_OWN_CAR, FLAG_OWN_REALTY, FLAG_LAST_APPL_PER_CONTRACT, EMERGENCYSTATE_MODE - varchar(5) (Для коротких текстовых меток и флагов)
- AMT_INCOME_TOTAL, AMT_CREDIT, AMT_ANNUITY, AMT_GOODS_PRICE, REGION_POPULATION_RELATIVE, OWN_CAR_AGE, EXT_SOURCE_1, EXT_SOURCE_2, EXT_SOURCE_3, ..._AVG, ..._MODE, ..._MEDI, TOTALAREA_MODE - real (для всех дробных показателей, коэффициентов и сумм)
- DAYS_BIRTH, DAYS_EMPLOYED, DAYS_ID_PUBLISH, HOUR_APPR_PROCESS_START - integer (Целые числа)
- CNT_CHILDREN, CNT_FAM_MEMBERS, REGION_RATING_CLIENT, REGION_RATING_CLIENT_W_CITY, ...CNT_SOCIAL_CIRCLE, AMT_REQ_CREDIT_BUREAU... - real (Используем real, так как в CSV эти счетчики часто идут в формате "0.0" и содержат NULL)
- DAYS_REGISTRATION, DAYS_LAST_PHONE_CHANGE - real (В CSV значения с дробной частью)
- TARGET, FLAG_MOBIL, FLAG_EMP_PHONE, FLAG_WORK_PHONE, FLAG_CONT_MOBILE, FLAG_PHONE, FLAG_EMAIL, REG_REGION_..., LIVE_REGION_..., REG_CITY_..., LIVE_CITY_..., FLAG_DOCUMENT_... - smallint (Бинарные флаги 0/1)

In [ ]:
table_name = "application"
sql_schema_query = f"""
    DROP TABLE IF EXISTS {table_name}; 
    CREATE TABLE {table_name}(
        SK_ID_CURR integer,
        TARGET smallint,
        NAME_CONTRACT_TYPE varchar(20),
        CODE_GENDER varchar(5),
        FLAG_OWN_CAR varchar(5),
        FLAG_OWN_REALTY varchar(5),
        CNT_CHILDREN real,
        AMT_INCOME_TOTAL real,
        AMT_CREDIT real,
        AMT_ANNUITY real,
        AMT_GOODS_PRICE real,
        NAME_TYPE_SUITE varchar(25),
        NAME_INCOME_TYPE varchar(25),
        NAME_EDUCATION_TYPE varchar(40),
        NAME_FAMILY_STATUS varchar(25),
        NAME_HOUSING_TYPE varchar(25),
        REGION_POPULATION_RELATIVE real,
        DAYS_BIRTH integer,
        DAYS_EMPLOYED integer,
        DAYS_REGISTRATION real,
        DAYS_ID_PUBLISH integer,
        OWN_CAR_AGE real,
        FLAG_MOBIL smallint,
        FLAG_EMP_PHONE smallint,
        FLAG_WORK_PHONE smallint,
        FLAG_CONT_MOBILE smallint,
        FLAG_PHONE smallint,
        FLAG_EMAIL smallint,
        OCCUPATION_TYPE varchar(30),
        CNT_FAM_MEMBERS real,
        REGION_RATING_CLIENT real,
        REGION_RATING_CLIENT_W_CITY real,
        WEEKDAY_APPR_PROCESS_START varchar(15),
        HOUR_APPR_PROCESS_START integer,
        REG_REGION_NOT_LIVE_REGION smallint,
        REG_REGION_NOT_WORK_REGION smallint,
        LIVE_REGION_NOT_WORK_REGION smallint,
        REG_CITY_NOT_LIVE_CITY smallint,
        REG_CITY_NOT_WORK_CITY smallint,
        LIVE_CITY_NOT_WORK_CITY smallint,
        ORGANIZATION_TYPE varchar(60),
        EXT_SOURCE_1 real,
        EXT_SOURCE_2 real,
        EXT_SOURCE_3 real,
        APARTMENTS_AVG real,
        BASEMENTAREA_AVG real,
        YEARS_BEGINEXPLUATATION_AVG real,
        YEARS_BUILD_AVG real,
        COMMONAREA_AVG real,
        ELEVATORS_AVG real,
        ENTRANCES_AVG real,
        FLOORSMAX_AVG real,
        FLOORSMIN_AVG real,
        LANDAREA_AVG real,
        LIVINGAPARTMENTS_AVG real,
        LIVINGAREA_AVG real,
        NONLIVINGAPARTMENTS_AVG real,
        NONLIVINGAREA_AVG real,
        APARTMENTS_MODE real,
        BASEMENTAREA_MODE real,
        YEARS_BEGINEXPLUATATION_MODE real,
        YEARS_BUILD_MODE real,
        COMMONAREA_MODE real,
        ELEVATORS_MODE real,
        ENTRANCES_MODE real,
        FLOORSMAX_MODE real,
        FLOORSMIN_MODE real,
        LANDAREA_MODE real,
        LIVINGAPARTMENTS_MODE real,
        LIVINGAREA_MODE real,
        NONLIVINGAPARTMENTS_MODE real,
        NONLIVINGAREA_MODE real,
        APARTMENTS_MEDI real,
        BASEMENTAREA_MEDI real,
        YEARS_BEGINEXPLUATATION_MEDI real,
        YEARS_BUILD_MEDI real,
        COMMONAREA_MEDI real,
        ELEVATORS_MEDI real,
        ENTRANCES_MEDI real,
        FLOORSMAX_MEDI real,
        FLOORSMIN_MEDI real,
        LANDAREA_MEDI real,
        LIVINGAPARTMENTS_MEDI real,
        LIVINGAREA_MEDI real,
        NONLIVINGAPARTMENTS_MEDI real,
        NONLIVINGAREA_MEDI real,
        FONDKAPREMONT_MODE varchar(30),
        HOUSETYPE_MODE varchar(30),
        TOTALAREA_MODE real,
        WALLSMATERIAL_MODE varchar(25),
        EMERGENCYSTATE_MODE varchar(10),
        OBS_30_CNT_SOCIAL_CIRCLE real,
        DEF_30_CNT_SOCIAL_CIRCLE real,
        OBS_60_CNT_SOCIAL_CIRCLE real,
        DEF_60_CNT_SOCIAL_CIRCLE real,
        DAYS_LAST_PHONE_CHANGE real,
        FLAG_DOCUMENT_2 smallint,
        FLAG_DOCUMENT_3 smallint,
        FLAG_DOCUMENT_4 smallint,
        FLAG_DOCUMENT_5 smallint,
        FLAG_DOCUMENT_6 smallint,
        FLAG_DOCUMENT_7 smallint,
        FLAG_DOCUMENT_8 smallint,
        FLAG_DOCUMENT_9 smallint,
        FLAG_DOCUMENT_10 smallint,
        FLAG_DOCUMENT_11 smallint,
        FLAG_DOCUMENT_12 smallint,
        FLAG_DOCUMENT_13 smallint,
        FLAG_DOCUMENT_14 smallint,
        FLAG_DOCUMENT_15 smallint,
        FLAG_DOCUMENT_16 smallint,
        FLAG_DOCUMENT_17 smallint,
        FLAG_DOCUMENT_18 smallint,
        FLAG_DOCUMENT_19 smallint,
        FLAG_DOCUMENT_20 smallint,
        FLAG_DOCUMENT_21 smallint,
        AMT_REQ_CREDIT_BUREAU_HOUR real,
        AMT_REQ_CREDIT_BUREAU_DAY real,
        AMT_REQ_CREDIT_BUREAU_WEEK real,
        AMT_REQ_CREDIT_BUREAU_MON real,
        AMT_REQ_CREDIT_BUREAU_QRT real,
        AMT_REQ_CREDIT_BUREAU_YEAR real
    )
"""

db_manager.send_sql_query(sql_schema_query)

Время выполнения: 0:00:00

SQL-запрос для заполнения таблицы данными из csv-файла

In [ ]:
table_name = "application"
sql_data_query = f"""
    COPY {table_name}(
        SK_ID_CURR,
        TARGET,
        NAME_CONTRACT_TYPE,
        CODE_GENDER,
        FLAG_OWN_CAR,
        FLAG_OWN_REALTY,
        CNT_CHILDREN,
        AMT_INCOME_TOTAL,
        AMT_CREDIT,
        AMT_ANNUITY,
        AMT_GOODS_PRICE,
        NAME_TYPE_SUITE,
        NAME_INCOME_TYPE,
        NAME_EDUCATION_TYPE,
        NAME_FAMILY_STATUS,
        NAME_HOUSING_TYPE,
        REGION_POPULATION_RELATIVE,
        DAYS_BIRTH,
        DAYS_EMPLOYED,
        DAYS_REGISTRATION,
        DAYS_ID_PUBLISH,
        OWN_CAR_AGE,
        FLAG_MOBIL,
        FLAG_EMP_PHONE,
        FLAG_WORK_PHONE,
        FLAG_CONT_MOBILE,
        FLAG_PHONE,
        FLAG_EMAIL,
        OCCUPATION_TYPE,
        CNT_FAM_MEMBERS,
        REGION_RATING_CLIENT,
        REGION_RATING_CLIENT_W_CITY,
        WEEKDAY_APPR_PROCESS_START,
        HOUR_APPR_PROCESS_START,
        REG_REGION_NOT_LIVE_REGION,
        REG_REGION_NOT_WORK_REGION,
        LIVE_REGION_NOT_WORK_REGION,
        REG_CITY_NOT_LIVE_CITY,
        REG_CITY_NOT_WORK_CITY,
        LIVE_CITY_NOT_WORK_CITY,
        ORGANIZATION_TYPE,
        EXT_SOURCE_1,
        EXT_SOURCE_2,
        EXT_SOURCE_3,
        APARTMENTS_AVG,
        BASEMENTAREA_AVG,
        YEARS_BEGINEXPLUATATION_AVG,
        YEARS_BUILD_AVG,
        COMMONAREA_AVG,
        ELEVATORS_AVG,
        ENTRANCES_AVG,
        FLOORSMAX_AVG,
        FLOORSMIN_AVG,
        LANDAREA_AVG,
        LIVINGAPARTMENTS_AVG,
        LIVINGAREA_AVG,
        NONLIVINGAPARTMENTS_AVG,
        NONLIVINGAREA_AVG,
        APARTMENTS_MODE,
        BASEMENTAREA_MODE,
        YEARS_BEGINEXPLUATATION_MODE,
        YEARS_BUILD_MODE,
        COMMONAREA_MODE,
        ELEVATORS_MODE,
        ENTRANCES_MODE,
        FLOORSMAX_MODE,
        FLOORSMIN_MODE,
        LANDAREA_MODE,
        LIVINGAPARTMENTS_MODE,
        LIVINGAREA_MODE,
        NONLIVINGAPARTMENTS_MODE,
        NONLIVINGAREA_MODE,
        APARTMENTS_MEDI,
        BASEMENTAREA_MEDI,
        YEARS_BEGINEXPLUATATION_MEDI,
        YEARS_BUILD_MEDI,
        COMMONAREA_MEDI,
        ELEVATORS_MEDI,
        ENTRANCES_MEDI,
        FLOORSMAX_MEDI,
        FLOORSMIN_MEDI,
        LANDAREA_MEDI,
        LIVINGAPARTMENTS_MEDI,
        LIVINGAREA_MEDI,
        NONLIVINGAPARTMENTS_MEDI,
        NONLIVINGAREA_MEDI,
        FONDKAPREMONT_MODE,
        HOUSETYPE_MODE,
        TOTALAREA_MODE,
        WALLSMATERIAL_MODE,
        EMERGENCYSTATE_MODE,
        OBS_30_CNT_SOCIAL_CIRCLE,
        DEF_30_CNT_SOCIAL_CIRCLE,
        OBS_60_CNT_SOCIAL_CIRCLE,
        DEF_60_CNT_SOCIAL_CIRCLE,
        DAYS_LAST_PHONE_CHANGE,
        FLAG_DOCUMENT_2,
        FLAG_DOCUMENT_3,
        FLAG_DOCUMENT_4,
        FLAG_DOCUMENT_5,
        FLAG_DOCUMENT_6,
        FLAG_DOCUMENT_7,
        FLAG_DOCUMENT_8,
        FLAG_DOCUMENT_9,
        FLAG_DOCUMENT_10,
        FLAG_DOCUMENT_11,
        FLAG_DOCUMENT_12,
        FLAG_DOCUMENT_13,
        FLAG_DOCUMENT_14,
        FLAG_DOCUMENT_15,
        FLAG_DOCUMENT_16,
        FLAG_DOCUMENT_17,
        FLAG_DOCUMENT_18,
        FLAG_DOCUMENT_19,
        FLAG_DOCUMENT_20,
        FLAG_DOCUMENT_21,
        AMT_REQ_CREDIT_BUREAU_HOUR,
        AMT_REQ_CREDIT_BUREAU_DAY,
        AMT_REQ_CREDIT_BUREAU_WEEK,
        AMT_REQ_CREDIT_BUREAU_MON,
        AMT_REQ_CREDIT_BUREAU_QRT,
        AMT_REQ_CREDIT_BUREAU_YEAR
    )
    FROM '{DATA_FULL_PATH}/{table_name}_train.csv' DELIMITER ',' CSV HEADER;
"""

db_manager.send_sql_query(sql_data_query)

Время выполнения: 0:00:06

In [ ]:
table_name = "application"
sql_data_query = f"""
    COPY {table_name}(
        SK_ID_CURR,
        NAME_CONTRACT_TYPE,
        CODE_GENDER,
        FLAG_OWN_CAR,
        FLAG_OWN_REALTY,
        CNT_CHILDREN,
        AMT_INCOME_TOTAL,
        AMT_CREDIT,
        AMT_ANNUITY,
        AMT_GOODS_PRICE,
        NAME_TYPE_SUITE,
        NAME_INCOME_TYPE,
        NAME_EDUCATION_TYPE,
        NAME_FAMILY_STATUS,
        NAME_HOUSING_TYPE,
        REGION_POPULATION_RELATIVE,
        DAYS_BIRTH,
        DAYS_EMPLOYED,
        DAYS_REGISTRATION,
        DAYS_ID_PUBLISH,
        OWN_CAR_AGE,
        FLAG_MOBIL,
        FLAG_EMP_PHONE,
        FLAG_WORK_PHONE,
        FLAG_CONT_MOBILE,
        FLAG_PHONE,
        FLAG_EMAIL,
        OCCUPATION_TYPE,
        CNT_FAM_MEMBERS,
        REGION_RATING_CLIENT,
        REGION_RATING_CLIENT_W_CITY,
        WEEKDAY_APPR_PROCESS_START,
        HOUR_APPR_PROCESS_START,
        REG_REGION_NOT_LIVE_REGION,
        REG_REGION_NOT_WORK_REGION,
        LIVE_REGION_NOT_WORK_REGION,
        REG_CITY_NOT_LIVE_CITY,
        REG_CITY_NOT_WORK_CITY,
        LIVE_CITY_NOT_WORK_CITY,
        ORGANIZATION_TYPE,
        EXT_SOURCE_1,
        EXT_SOURCE_2,
        EXT_SOURCE_3,
        APARTMENTS_AVG,
        BASEMENTAREA_AVG,
        YEARS_BEGINEXPLUATATION_AVG,
        YEARS_BUILD_AVG,
        COMMONAREA_AVG,
        ELEVATORS_AVG,
        ENTRANCES_AVG,
        FLOORSMAX_AVG,
        FLOORSMIN_AVG,
        LANDAREA_AVG,
        LIVINGAPARTMENTS_AVG,
        LIVINGAREA_AVG,
        NONLIVINGAPARTMENTS_AVG,
        NONLIVINGAREA_AVG,
        APARTMENTS_MODE,
        BASEMENTAREA_MODE,
        YEARS_BEGINEXPLUATATION_MODE,
        YEARS_BUILD_MODE,
        COMMONAREA_MODE,
        ELEVATORS_MODE,
        ENTRANCES_MODE,
        FLOORSMAX_MODE,
        FLOORSMIN_MODE,
        LANDAREA_MODE,
        LIVINGAPARTMENTS_MODE,
        LIVINGAREA_MODE,
        NONLIVINGAPARTMENTS_MODE,
        NONLIVINGAREA_MODE,
        APARTMENTS_MEDI,
        BASEMENTAREA_MEDI,
        YEARS_BEGINEXPLUATATION_MEDI,
        YEARS_BUILD_MEDI,
        COMMONAREA_MEDI,
        ELEVATORS_MEDI,
        ENTRANCES_MEDI,
        FLOORSMAX_MEDI,
        FLOORSMIN_MEDI,
        LANDAREA_MEDI,
        LIVINGAPARTMENTS_MEDI,
        LIVINGAREA_MEDI,
        NONLIVINGAPARTMENTS_MEDI,
        NONLIVINGAREA_MEDI,
        FONDKAPREMONT_MODE,
        HOUSETYPE_MODE,
        TOTALAREA_MODE,
        WALLSMATERIAL_MODE,
        EMERGENCYSTATE_MODE,
        OBS_30_CNT_SOCIAL_CIRCLE,
        DEF_30_CNT_SOCIAL_CIRCLE,
        OBS_60_CNT_SOCIAL_CIRCLE,
        DEF_60_CNT_SOCIAL_CIRCLE,
        DAYS_LAST_PHONE_CHANGE,
        FLAG_DOCUMENT_2,
        FLAG_DOCUMENT_3,
        FLAG_DOCUMENT_4,
        FLAG_DOCUMENT_5,
        FLAG_DOCUMENT_6,
        FLAG_DOCUMENT_7,
        FLAG_DOCUMENT_8,
        FLAG_DOCUMENT_9,
        FLAG_DOCUMENT_10,
        FLAG_DOCUMENT_11,
        FLAG_DOCUMENT_12,
        FLAG_DOCUMENT_13,
        FLAG_DOCUMENT_14,
        FLAG_DOCUMENT_15,
        FLAG_DOCUMENT_16,
        FLAG_DOCUMENT_17,
        FLAG_DOCUMENT_18,
        FLAG_DOCUMENT_19,
        FLAG_DOCUMENT_20,
        FLAG_DOCUMENT_21,
        AMT_REQ_CREDIT_BUREAU_HOUR,
        AMT_REQ_CREDIT_BUREAU_DAY,
        AMT_REQ_CREDIT_BUREAU_WEEK,
        AMT_REQ_CREDIT_BUREAU_MON,
        AMT_REQ_CREDIT_BUREAU_QRT,
        AMT_REQ_CREDIT_BUREAU_YEAR
    )
    FROM '{DATA_FULL_PATH}/{table_name}_test.csv' DELIMITER ',' CSV HEADER;
"""

db_manager.send_sql_query(sql_data_query)

Время выполнения: 0:00:01

Вывод данных таблицы из БД

In [ ]:
table_name = "application"
sql_query = f"""
    SELECT * FROM {table_name}
    LIMIT 10
"""

df = db_manager.get_df_from_query(sql_query)
df

Время выполнения: 0:00:00

,sk_id_curr,target,name_contract_type,code_gender,flag_own_car,flag_own_realty,cnt_children,amt_income_total,amt_credit,amt_annuity,...,flag_document_18,flag_document_19,flag_document_20,flag_document_21,amt_req_credit_bureau_hour,amt_req_credit_bureau_day,amt_req_credit_bureau_week,amt_req_credit_bureau_mon,amt_req_credit_bureau_qrt,amt_req_credit_bureau_year
0,100002,1,Cash loans,M,N,Y,0.0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0.0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0.0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0.0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0.0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
5,100008,0,Cash loans,M,N,Y,0.0,99000.0,490495.5,27517.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
6,100009,0,Cash loans,F,Y,Y,1.0,171000.0,1560726.0,41301.0,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,2.0
7,100010,0,Cash loans,M,Y,Y,0.0,360000.0,1530000.0,42075.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
8,100011,0,Cash loans,F,N,Y,0.0,112500.0,1019610.0,33826.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
9,100012,0,Revolving loans,M,N,Y,0.0,135000.0,405000.0,20250.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

## Создадим некоторые индексы для оптимизации запросов, а также определим первичные и внешние ключи

In [72]:
sql_keys_query = """
    ALTER TABLE application ADD PRIMARY KEY (SK_ID_CURR);

    ALTER TABLE bureau ADD PRIMARY KEY (SK_ID_BUREAU);

    ALTER TABLE bureau_balance ADD PRIMARY KEY (SK_ID_BUREAU, MONTHS_BALANCE);

    ALTER TABLE pos_cash_balance ADD PRIMARY KEY (SK_ID_PREV, MONTHS_BALANCE);
    
    ALTER TABLE credit_card_balance ADD PRIMARY KEY (SK_ID_PREV, MONTHS_BALANCE);

    ALTER TABLE previous_application ADD PRIMARY KEY (SK_ID_PREV);
"""

db_manager.send_sql_query(sql_keys_query)

Время выполнения: 0:01:56

Для таблиц вместо внешних ключей лучше создать индексы, чтобы не было ошибок при импорте информации оттуда из-за отсутствия значений внешних ключей.

- Некоторые индексы были созданы вместо внешних ключей, потому что при создании внешнего ключа возникала ошибка из-за пропусков в данных (idx_bureau_bal_sk_id_bureau и др.)
- Индексы idx_app_target и idx_app_income_type ускоряют запросы WHERE и группировки по этим полям
- Индексы на SK_ID_CURR в дочерних таблицах нужны для оптимизации операций JOIN с таблицей application
- Часто индексы используются для статусов, потому что они могут использоваться в WHERE во многих запросах

In [73]:
sql_index_query = """
    CREATE INDEX IF NOT EXISTS idx_bureau_bal_sk_id_bureau ON bureau_balance(SK_ID_BUREAU);

    CREATE INDEX IF NOT EXISTS idx_app ON application(TARGET);
    CREATE INDEX IF NOT EXISTS idx_app_income_type ON application(NAME_INCOME_TYPE);

    CREATE INDEX IF NOT EXISTS idx_bureau_curr ON bureau(SK_ID_CURR);
    CREATE INDEX IF NOT EXISTS idx_prev_app_curr ON previous_application(SK_ID_CURR);
    CREATE INDEX IF NOT EXISTS idx_pos_cash_curr ON pos_cash_balance(SK_ID_CURR);
    CREATE INDEX IF NOT EXISTS idx_inst_pay_curr ON installments_payments(SK_ID_CURR);
    CREATE INDEX IF NOT EXISTS idx_cc_bal_curr ON credit_card_balance(SK_ID_CURR);

    CREATE INDEX IF NOT EXISTS idx_prev_app_status ON previous_application(NAME_CONTRACT_STATUS);
    CREATE INDEX IF NOT EXISTS idx_bureau_active ON bureau(CREDIT_ACTIVE);
"""

db_manager.send_sql_query(sql_index_query)

Время выполнения: 0:01:12